### ISSUE TITLE
sync manager: cancelling a registered job did not work.

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1013]
I started a prepare_all and then tried to cancel one of the "pending" jobs. The job switched to CANCELLING but never cancelled. And it kept blocking the remaining pending job.

**Comment by urapadmin** [comment]
### @test 0.11
- [ ] if a job is "pending" and gets cancelled in that state it should cancel right away and show "the last task got cancelled". 
- [ ] it should neither block any other pending process from starting
- [ ] the workstation offers to run a new task right away and starting one works

**Comment by lbestock** [comment]
This looked wrong but worked properly when in PVD local on my iPad in portrait mode. As in, it never said cancelled, and it never stopped saying processing, though it got an extra bar, but it did in fact stop that job and did not prevent the processing of those workstations after it. And I was then able to go and fork the one that had been cancelled, with no problem, though I didn't try that until after the other two were done.
![image](https://user-images.githubusercontent.com/49291909/115157961-dd48c780-a059-11eb-8fb2-771627697f9f.png)

**Comment by lbestock** [comment]
No problem starting another task in the cancelled workstation while the others are still running, and it moves it to the end of the queue. Portrait/landscape makes no difference except to where it displays the extra blank box - still no "cancelled" is shown. The same thing happens when I'm on my Mac. The process I started was "prepare everything for the field". The return is different if I cancel something while the running operation is "reset all workstations":
![image](https://user-images.githubusercontent.com/49291909/115158165-ebe3ae80-a05a-11eb-9a35-dcc7157879b6.png)
But it still doesn't stop later stuff from happening and it still allows me to go in and start a new process with no problem.
