### ISSUE TITLE
File Picking: record_type NOT IN

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1018]
The "record_type" rule can now use "NOT IN" or "!IN" as described in the wiki: 
[https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:file_picking](https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:file_picking#rule_types)

**Comment by urapadmin** [comment]
### @test kiosk 0.11
- [ ] !IN / NOT IN operator for rule record_type

**Comment by luizaogs** [comment]
So this works but I have a question. I used the record_type !in dayplan results in dummies rule, for the record.

Do plans and photos for survey units and features fall under dayplans? Because they are not dummies after applying this rule, so I suppose they are counting as dayplans at the moment. If they are supposed to count as dayplans then we are good!

**Comment by urapadmin** [comment]
yes. the record type "dayplan" has always been a somewhat misleading term. We are talking about the list of images on unit level. record type really addresses all records in a certain table (if that statement helps anything).

**Comment by luizaogs** [comment]
It helps indeed, and I can close this.
