### ISSUE TITLE
quality control: dialog showing intelligible hints and warnings

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1044]

**Comment by luizaogs** [comment]
This is cool! And works perfectly, as far as I can tell. Just one question: when there are only hints left the title is green but the hint itself in the list is white as it was before (see below) -- should those match, or was that intentional? If intentional, this can be closed (and that last box can be checked).

![image](https://user-images.githubusercontent.com/67970402/116798715-ed848c00-aac8-11eb-9d6f-a36ceca33b99.png)

**Comment by urapadmin** [comment]
well, yes. I defined the hints to have no background here. 
That can be changed on a project basis in the configuration under css/qc_messages_css by __adding__ something like 
`.hint {
      background-color: deeppink;
      color: black;
  }`

to the configuration setting. It makes it deep pink, which is awful but easy to test :o)

**Comment by luizaogs** [comment]
I thought that was the case :) Ok, closed!
