### ISSUE TITLE
housekeeping in synchronization produces a lot of errors that confuse users

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1084]
not sure what to do. Suppress them within synchronization? At least I should mark clearly in the log where synchronization ends and where Housekeeping starts in the log

**Comment by urapadmin** [comment]
### @test kiosk 0.11.8
- [ ] as a first step I have degraded a few errors to warnings and added a separator BUT that won't help much.
- [ ] as a second step I have added lines that separate the synchronization part from the housekeeping part and inform the user about what is going on.

**Comment by luizaogs** [comment]
I'll be honest and say that I don't know if I can check the first box because I don't know what you changed (and I'm also not super familiar with synchronization to judge). 

BUT I saw the line that splits housekeeping from the rest just now and thought it was helpful. I wonder, though, if making it white rather than green would be more successful in catching a user's attention? Just because I had a bunch of green lines above that so I didn't initially see the difference, only spotted it because I was looking for it. Or maybe add a space or something? Not sure if that's possible. But I think it works well as is, too!

**Comment by urapadmin** [comment]
It will stay green, because is says "success", but I think I can invent the possibility to have separating lines in the log. That might be the best choice here. I'll go with that. But in a different ticket.

**Comment by urapadmin** [comment]
so we can close this here, I think
