### ISSUE TITLE
file repos: show file size and file type

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1088]
showing the file size and file type of the original file would be useful at times

**Comment by urapadmin** [comment]
### @test 0.13.4
file type and file size (if accessible) of the original file are shown in the upper right corner.

**Comment by luizaogs** [comment]
The file type is always there, but I haven't seen any file sizes yet (the ? appears where the size should be). I know you say "if accessible" above so I'm guessing this is not an issue, but since I've opened a zillion different types of files (pdfs, uploads, sketches, ipad photos) to check whether any sizes appeared and they did not I thought I would mention it.

**Comment by urapadmin** [comment]
ja, the ? should be the exception rather than normal. I'll call that a bug which might surface only on Beset.

**Comment by urapadmin** [comment]
### @test kiosk 0.13.6
it was a bug: fixed.
