### ISSUE TITLE
fileimport: s'Urachi can't import photos for loci or collected material

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1091]
because that would be ambiguous. If the file import allowed to preselect the record type that limitation could be overcome.

**Comment by lbestock** [comment]
Will work for loci, but is not enough alone in the case of CM, where here might be ceramics, bone, glass, etc all different records but all locus X, CM.

**Comment by urapadmin** [comment]
ja, you have got a point there. So that's not a solution. I close it.

**Comment by urapadmin** [comment]
So I see two alternatives:
- [ ] the collected material gets an identifier with the material as a suffix. So 3042C is ceramics, 3042B is bones. In fact s'Urachi is already doing this somewhere because, well, after all those numbers are not only ambiguous for the file import
- [ ] we create something like a technical identifier that nobody uses except when it comes to the file import. It is like an alternative number but auto generated by the system.

**Comment by lbestock** [comment]
The former might very well catch what some projects do, and so I incline that way. I remember Zach's numbering, though it wasn't this but rather this PLUS URAP structured number style. So he'd have ContextX.C.001 and ContextX.M.001 and ContextX.M.002. But also as you say, s'Urachi might not recognize that this is what they are doing when they tag things but it is in effect what they are doing by selecting material. It's also an easier solution to imagine from the user's perspective because you learn the suffixes once. With a technical identifier you would need to be in the system to see what it is while preparing the import. With C, B etc you don't.

**Comment by urapadmin** [comment]
s'Urachi should be able to use qr codes once the material designator is part of the identifier, which is the plan.

**Comment by lbestock** [comment]
I have failed with my attempt to do QR code photo uploads. My first failure I thought might be because the glare on the iPad and the size of it in the drone shots might have been troublesome, but I tried it again with an indoor closeup of the QR code board and it did not work.
![image](https://user-images.githubusercontent.com/49291909/121718838-bbdfe700-cab0-11eb-92cd-1a7cd5ffb38b.png)
(You can see in the director's view that this collected material exists and has been synchronized.)
Attached are two of the photos I tried to import, same CM number.
![IMG_7104](https://user-images.githubusercontent.com/49291909/121719734-f3e72a00-cab0-11eb-9d89-23f9bc3979cb.JPG)
![DJI_0004](https://user-images.githubusercontent.com/49291909/121719942-ff3a5580-cab0-11eb-8d86-b09577a08b13.JPG)

**Comment by urapadmin** [comment]
can't work. S'Urachi is configured like USTP when it comes to loci / collected material photos. BUT the identifier in the error code is correct, right? Did it recognize the one on the drone photo, too?

**Comment by lbestock** [comment]
Ah I didn't look - I will try it again!

**Comment by urapadmin** [comment]
That ipad is too schmutzig. Kapersky at least cannot identify the qr code on the photo.

**Comment by lbestock** [comment]
Really? Because the file import just got it no problem. And got harder ones. It got all of them except one from the drone, and that was one I took at an angle.

**Comment by lbestock** [comment]
![image](https://user-images.githubusercontent.com/49291909/121721643-791f0e80-cab2-11eb-8c00-d2f99b665966.png)

That is pretty amazing.

**Comment by lbestock** [comment]
I mean, it even got this one: 

![DJI_0008](https://user-images.githubusercontent.com/49291909/121721763-9c49be00-cab2-11eb-9423-ae2e351b882e.JPG)

**Comment by urapadmin** [comment]
I am glad to hear we beat Kapersky :)

**Comment by urapadmin** [comment]
you can do this now. But what kind of identifier is SU21AA001B? IS the first A the context and the second the material code? But what is the B?

**Comment by urapadmin** [comment]
ah, the file repository helped me:
![image](https://user-images.githubusercontent.com/38838314/122448228-d3353d80-cfa4-11eb-80ef-656c652d3443.png)
AA is the unit and 001B the context. This is all pretty confusing to me.

**Comment by urapadmin** [comment]
Is there something wrong or does that mean it works and we can close this?

**Comment by lbestock** [comment]
It works and we can close this.
