### ISSUE TITLE
issue with !IN / NOT IN operator -- not context bound?

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1097]
Came out of testing #1018 but I thought it warranted a new ticket since it seemed bug-y. 

I used the record_type !in dayplan results in dummies rule. However, site maps were turned to dummies. In the wiki you say that this rule only works for context-bound images, so that seemed incorrect to me. Is it? 

Side note: hm, how does one label a ticket relating to file picking? I did both kiosk and filemaker since it seems to affect both but not sure if that is the best way!

**Comment by luizaogs** [comment]
A screenshot of the rule I used in case the explanation above is not sufficient, since I need to delete it to test something else: 

![image](https://user-images.githubusercontent.com/67970402/118414016-47ac5200-b670-11eb-9807-519d3c7cdccf.png)

**Comment by luizaogs** [comment]
Ok, same issue with the site maps when testing #1017. So it seems like the !in/not in rules are not only applying to context-bound images at the moment?

**Comment by urapadmin** [comment]
To really understand what you are doing I would need ALL rules. I suspect rule #1 as setting all contextuals to low? And then you wanted to exclude everything that is NOT in dayplans? 

Anyways, poor you have learned about file picking from that wiki article of mine that I wrote more or less as a reference for myself and never got any explanation. So I am astonished you even made it that far. 
"context"-bound does not mean "locus"-bound. In kiosk a context is a key concept that is more abstract than the archaeological "context". That might be where some confusion comes from? I am not sure. If you are interested: I monologued on it here: [https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:on_contexts_and_identifiers](https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:on_contexts_and_identifiers).

Should you have better things to read, here is the gist:
A context brackets all data that can be bound to an identifier. So the site context can include the units, loci, materials, small finds etc. and the central handle of it all would be the identifier of a site. We define a "scope" for a context depending on its use case. Of course, the archaeological "context" is A context. But so is a site, a collected material and even a tag. 

So site maps are context-bound: bound to the context "site". In the file repository you get them by typing in the site's identifier. (You don't get all the locus and unit images only because we have limited the scope for a site's context for the file repository).

Back to your rule: 
0. sets everything to dummy
1. "contextuals" sets everything that can be bound to an identifier to "low"
2. "record_type" !IN sets everything that is not in dayplan (your site maps aren't, I suppose) to dummy. 

So your site maps should be dummies. 

And one day I write you and everybody a wiki article on file picking that actually explains something :o)

**Comment by urapadmin** [comment]
Don't worry too much about whether file picking is rather kiosk or filemaker. You are right that depending on the issue often only I can decide where the problem really lies. Use "kiosk" since most of its logic is at home there.

**Comment by luizaogs** [comment]
Ha, I enjoyed your Wittgensteinian monologue (and now kinda want to eat risotto but it's 7am). Yes, the confusion was definitely on the "context" front, so this can be closed. But what is NOT context-bound, then? Candids?

Your file picking wiki stuff was a bit mysterious but once I figured out where and how to actually define the rules at all it became much easier :)
