### ISSUE TITLE
"dayplans" vs "dayplan" when using !in/not in rule

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1098]
When testing #1018 I originally tried the rule "record_type !in dayplanS results in dummies" (note the plural in dayplans) and literally everything became a dummy. Which seems bug-y? I used "dayplans" because that's what you had in the wiki (in the "!IN" (or "NOT IN") section of the file picking page: https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:file_picking#rule_types) and before I checked the recording context aliases page and saw that it should indeed be "dayplan" in the singular. So maybe also worth changing that "dayplans" to "dayplan" in the wiki, in the file picking rules page? But should this rule have been applied at all (resulting in everything becoming a dummy), since I used the wrong value?

The rule that later actually worked, in case the stuff above is unclear. So the incorrect one that led to all dummies was just "dayplans" rather than "dayplan".
![image](https://user-images.githubusercontent.com/67970402/118414433-83481b80-b672-11eb-987a-5e3399749b4b.png)

**Comment by urapadmin** [comment]
it correct that when setting everything that is not a certain record type (even if that record type is unknown) to dummy the result is that everything becomes a dummy. Because nothing is of that record type. That is what your were doing, right? 

The dayplan/dayplans thing is so typical, I really tried to decide in the very beginning whether I should call things singular and plural. And then I made a mess. And after all these years I don't know anymore. I will update the wiki article. "dayplan" is definitely the correct name of the record type.

**Comment by luizaogs** [comment]
I do have editing rights, but since I hardly knew what I was doing myself I didn't want to mess it up!

And yes, if the idea is that the rule should be applied even if the record type is unknown then this isn't an issue. I don't know if having a warning or something that the user inserted an unknown record type would be useful, though? Because it threw me off at first that everything was dummified since I thought I had inserted the correct value, so knowing that I had done so before downloading the database might have been helpful. But I don't know if this is an issue that would be relevant to anything other than testing (and testing by Luiza, specifically)!

**Comment by urapadmin** [comment]
I leave it entirely in your judgement if you can improve things or not. I just wanted to make sure that you can and that you know you may. The wiki needs help on many a front. 

As for the main topic: The ui you use is entirely provisional. One day file picking and quality control and all the other things you see in this admin section are supposed to have real user interfaces that guide users and help them make the right decisions and translate it into the cryptic form you are using currently. One day. The user interfaces in the admin section are generic and cannot be improved: #1021

Since the file picking results can become pretty opaque, I thought I already had a ticket for a user interface that "explains" why a certain file gets its resolution. Can't find it, so here is a new one:

**Comment by urapadmin** [comment]
so I think this ticket here can be closed, now, right?

**Comment by luizaogs** [comment]
Ah I see. Yup, closing.
