### ISSUE TITLE
collected material list: material should have more space

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1104]
![image](https://user-images.githubusercontent.com/38838314/118897371-18981980-b8d8-11eb-8a21-b72f50fed856.png)

**Comment by urapadmin** [comment]
and here
![image](https://user-images.githubusercontent.com/38838314/118897437-4715f480-b8d8-11eb-8c06-be3ab4293c5e.png)

**Comment by urapadmin** [comment]
### @test 10.6.2
There is more space now. It is not possible in the header in the selection list.

**Comment by luizaogs** [comment]
This all looks good (both in the collected material list and in the collected material form), I'm just wondering if you want to move "small find" and "type" a bit to the right in the collected materials locus list? There seems to be a lot of room left there and they look a bit crowded (see below). But this is pickiness and I think it is good to go if you don't want to deal with the pickiness :)

![image](https://user-images.githubusercontent.com/67970402/120243180-503e8400-c23d-11eb-965e-e254875118a0.png)

**Comment by lbestock** [comment]
It's not really a test for s'Urachi because there are no small finds in the s'Urachi CM. So everything looks nice and spaced out there. In PVD it still looks pretty smushed and I think there is room to space it out a bit more - I've chosen the longest current possibility for type and it seems to me still room to move it a bit to the right and let small find breathe. I have no problem with small find being stacked; I even like it.
![image](https://user-images.githubusercontent.com/49291909/124354533-752a6c00-dbda-11eb-8813-1ea3e3352329.png)

**Comment by urapadmin** [comment]
I cannot make pvd different from su in such a list. I have to use the project with the longest material names as the limit
