### ISSUE TITLE
upload / download config files to kiosk

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1118]
a first and for v1 perhaps even sufficient step could be a UI that 

- simply lists all configuration files the server knows (we can configure that list in the config). The UI then allows to download those files or upload them again. 
-  Allowing a new file to be uploaded would mean that the new file has to be added to that list of config files, too.
- when uploading there should be at least a YAML validation for yaml files.

_Originally posted by @urapadmin in https://github.com/urapadmin/kiosk/issues/889#issuecomment-824529763_

**Comment by urapadmin** [comment]
As an addition (the download/upload should always be possible):

I also wonder if using an integrated code editor would be such a huge task. 
- look at [ace](https://ace.c9.io/) and [https://stackoverflow.com/questions/53140910/ace-editor-yaml-syntax-highlighting-error-on-a-non-quoted-string-starting-with-a](https://stackoverflow.com/questions/53140910/ace-editor-yaml-syntax-highlighting-error-on-a-non-quoted-string-starting-with-a)

**Comment by urapadmin** [comment]
see also #1085: There is the idea of a central download/upload module.
That might be a valid idea. What about defining a list of uploadable/downloadable files? Or directories to upload to. And some central uploader/downloader does it then. That way one could handle configuration files as well.

**Comment by urapadmin** [comment]
### @test 0.12
The new filemanager allows the upload and download of all kinds of files depending on a set of configured directories.
A short documentation is here.
- [ ] file manager accessible in administration if user has "enter administration" privilege
- [ ] configure directories for the file manager accessible in administration / file manager if and only if user has "manage server" privilege
- [ ] file manager shows configured directories as topics with a button to enter a topic
- [ ] on entering a topic all files in the directory are listed with appropriate actions
- [ ] inside a topic there is a upload section to upload a new or existing file
- [ ] if a file is deleted it can be restored
- [ ] if a file is overridden it can be restored

**Comment by luizaogs** [comment]
Question, for the second checkbox: I can totally configure directories as an admin, but in the wiki you say that the manage server privilege should be set explicitly because some features won't work if one only has the * set in the privilege field. So: is configuring topics something that is included in the * admin privilege or should I not have access to that menu item as an admin who does not have the manage server privilege explicitly set?

**Comment by luizaogs** [comment]
When deleting a file, I first got a warning that I could NOT delete it (but didn't have time to screenshot it before it disappeared). However, the file was evidently in fact deleted because I now have the restore button on there, only I apparently cannot restore it:

![Screen Shot 2021-07-23 at 6 24 30 PM](https://user-images.githubusercontent.com/67970402/126843057-07c63c84-c7c2-4415-8482-f0036c777708.png)

**Comment by luizaogs** [comment]
Two different things pertaining to my trying to override a file: 

1. When uploading a file again (pvd_Tue_160321-142732.dmp) to see if I could override and restore, I got 100% upload but then a warning that the upload had in fact not worked (the warning also disappeared too quickly for me to screenshot it -- maybe worth leaving them on for longer?). But I got the restore button there, so now I'm not sure if it was in fact uploaded or not: 
![Screen Shot 2021-07-23 at 6 29 48 PM](https://user-images.githubusercontent.com/67970402/126843621-69249b88-5537-43af-8fd9-eed5184d77c6.png)

2. There's apparently a size limit of 5 MBytes for uploads -- is this purposeful? I wondered because a lot of these files are larger than that, so then how can you re-upload a large file, for instance, if the limit seems lower than that of most of the existing files? 
![Screen Shot 2021-07-23 at 6 28 43 PM](https://user-images.githubusercontent.com/67970402/126843731-99ba816b-db38-484a-b667-d3993e0c3fc2.png)

**Comment by urapadmin** [comment]
> 
> 
> Question, for the second checkbox: I can totally configure directories as an admin, but in the wiki you say that the manage server privilege should be set explicitly because some features won't work if one only has the * set in the privilege field. So: is configuring topics something that is included in the * admin privilege or should I not have access to that menu item as an admin who does not have the manage server privilege explicitly set?
> 
> Oh this applies to the last checkboxes too, of course. The privilege for the backups topic for both modify and read is manage server, and I can both modify files (with the below caveats) and enter the topic. Should I be able to, with the general * privilege?

yes. The only privilege that has to be explicitly set is the developer privilege because we don't want it included for admins.

**Comment by urapadmin** [comment]
The Blimey! when you deleted and that you were not able to restore was due to missing privileges on OS level on Beset for the backup directory. I have added them and that should be fine now

**Comment by urapadmin** [comment]
### @test 0.13.2
- [ ] the max upload size is now configurable ([https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=kiosk_configuration:the_filemanagerplugin_section](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=kiosk_configuration:the_filemanagerplugin_section)). The default, if it is not configured, is 10 Megabytes.
I have configured it for PVD to be 25 MB.

**Comment by luizaogs** [comment]
Works!

**Comment by urapadmin** [comment]
### @test 0.13.15
I reopen this because of the recent Python / Flask update. It needs to be tested again.

**Comment by luizaogs** [comment]
Still works.
