### ISSUE TITLE
image descriptions in pinboard are amusingly wacky

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1189]
A funny one. I noticed that image descriptions were different in different pinboards, for the same image, it seems because the same image is in different places.

Go to context LA in PVD and pin the second dayplan -- the nice ice cream image that was a gift for Luiza. Open that pinboard in LA and you should get the image below: 
![Screen Shot 2021-07-26 at 9 21 33 PM](https://user-images.githubusercontent.com/67970402/127075617-bdf6bbd2-b6bd-43e2-8b28-36d9e8fee866.png)

Squiggles is another context, but this image is also there (I guess Laurel inserted it through the gallery). But I'm not sure you would want this image description, since I pinned the occurrence of the image in LA dayplans? 

Anyway, if you then go to the pinboard somewhere else (go to tag analysis because I know this was the case there), you'll get this: 
![Screen Shot 2021-07-26 at 9 22 52 PM](https://user-images.githubusercontent.com/67970402/127076029-5a96a1c9-26c9-4672-ae4c-1e3cac49ca45.png)

Which is funnier, because that's also not what I would expect after having pinned the image in LA dayplans, since this description matches collected material from LA-005 instead (where the image is also found, so that at least is not a problem).

So: how do you want the image descriptions to show up in the pinboard, if the image occurs in different places? The description of the image that was pinned? Currently does not seem to be the case.

**Comment by urapadmin** [comment]
ja, this is, erm, indertermined. What description appears in the pinboard is not set and has nothing to do with WHERE you pin the image. The image is always the same only the description is bound to the record type it had been inserted in. The pinboard works only predictably if an image is related to only one record type. I will have a look but I am not sure I will solve it for v1. In the end in real projects we rarely have an image attached to more than one record type.

**Comment by urapadmin** [comment]
looked it up. Indeed, filemaker makes a choice that I cannot control in this scenario. The place of pinning plays no role here (it could be the gallery itself, which is no place!) To really control this I would have to redesign the whole pinboard and I'd rather not. 
If the confusion outweighs the benefit of having at least one of the identifiers and descriptions going with an image we can simply get rid of that information.

**Comment by luizaogs** [comment]
Well my intention was not to cause you any pain, and if real projects rarely have an image attached to more than one record type I guess there would be little confusion involved?

Related but unrelated: I just noticed that in the second image I include above I say that the image is in collected material of context LA-005, but the identifier in the pinboard is the context rather than the CM (would be LA-005-7). Don’t know how relevant or painful that is, either.

**Comment by urapadmin** [comment]
all things can happen here. Filemaker selects one of the possible record types an attachement allowd. If you go to the gallery you see them all listed for the image. Any one of them is correct. So I cannot even control that fm selects a record the image had been directly attached to. The result is „something about the image“. I admit it is of dubious worth.

**Comment by luizaogs** [comment]
It's not of dubious worth, I hadn't checked the gallery. Ignore me.

**Comment by urapadmin** [comment]
misunderstanding, I guess. The information in the gallery is quite valuable. What I meant is the original issue that the pinboard shows random information about an image. And there I really think we should discuss if it is better to know something about an image (but more often not what you'd expect) or if we should just drop the description and identifiers and focus on the image itself because the other information is more often confusing than helpful. 
So I won't ignore you. No way.

But I have one more idea, I will try ...

**Comment by urapadmin** [comment]
... no. Defeated. With the current design of the pinboard this random behaviour (and it is actually random since it seems to be based on a random id) is just as it is. 
In fact even if an image is attached to only one record type it is not determined which id or description appears. So if I have a cm photo if could happen that instead of the descritpion and identifier of the cm you get the unit identifier and no description at all. 

Changing this would mean to find, change and test every single pin button in the recording system and every pin board. And that won't be in v1. So we should decide here whether we want to hide the information as it is now or live with its caprice.

**Comment by luizaogs** [comment]
Ah so that's more random than I realized. Maybe it's worth thinking about what the pinboard might be used for most often? If one is mostly pinning plans, which are more often than not labeled themselves, the label might not be necessary. That is what I, at least, envisioned the pinboard as most useful for. But if one is using the pinboard to compare soil colors of different contexts (which, why would you do that? Sounds like a terrible idea. But you get the point) -- or anything else that might be easily confused -- then I suppose descriptions, even if random, might help. Short answer is that I am not sure :) Director Laurel might have other ideas.

**Comment by lbestock** [comment]
I do not think this is something to lose sleep over because by definition one is only using the pinboard when one is in the middle of working on something - not a time one is likely to forget what it is or why it is relevant. One would use Munsells not photos for a meaningful comparison of soil colors - photos are notoriously bad for color. Wall construction techniques I can believe in more :) But as Lutz says, really are those wall construction photos going to be used in any place other than the context itself? Not likely in a real world scenario, so no confusion would arise. OK there I go in the specifics again! A totally ideal world would have a list of all the contexts where a thing is, and either all or none of the descriptions. But it is definitely not worth the effort even to hide stuff as the pinboard as is will work very well and will almost never result in confusion in the real world. So I close this.
