### ISSUE TITLE
timezone fun times

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1209]
I don't think this ever happened to me in Rio, which is why I'm documenting it because I'm not sure if something has changed (that should not have changed). 

My workstations are set to GMT-5, Chicago time. But I still got the following alert when opening it: 

![Screen Shot 2021-09-26 at 7 00 10 AM](https://user-images.githubusercontent.com/67970402/134807092-59d55d96-54d2-4382-b825-f883d509fc71.png)

So then I changed my laptop's time just to get the testing done and was going to document the above later, but then I got this alert, I guess because of the workstation setting:

![Screen Shot 2021-09-26 at 8 02 15 AM](https://user-images.githubusercontent.com/67970402/134807113-9c2e5636-cf34-495f-a6c3-a126f9be33c2.png)

So now I'm not sure what the best approach is? Do I just ignore the first alert? Help appreciated :)

**Comment by urapadmin** [comment]
As background:
Timezones are a hellish topic. It is correct, that you never saw the first message in Rio because Rio is East of Providence (right?), so GMT-3 or so. So you were an hour later than Providence. It is less problematic to be later than to be earlier than the server and that is why the first message appears now that you are GMT-5. But the compensation I implemented when Laurel was in CA seems to work alright so far. see #1184. So this first message will likely disappear once we have tested it a but longer. It really only alerts you to keep an eye in the issue and double check that your changes are properly synchronized.

The second message is old and tells you that your local computer is not set to the expected timezone. And that is due to you changing your time. So that looks okay.

What to do:
So from my perspective you can just test ignoring the first message rather than changing your device's time (which is a pain anyways).

**Comment by luizaogs** [comment]
Ok! I'll let you know if things don't go as planned when I ignore alert 1.

**Comment by urapadmin** [comment]
I close this since the original question is answered.
