### ISSUE TITLE
QC does not recognize change in context type

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1210]
Quality control does not recognize a change in context type and continues to report an error that is no longer relevant. I created a context of type "Architecture". I did not input a material (but did the bare minimum of other stuff to be allowed out of the record), which in PVD 11.3 is in violation of a QC rule. I then changed the context to type "cut", but I still get the warning that something seems not quite right and that I need to select a material for a context of type architecture.

**Comment by urapadmin** [comment]
this is, well not quite by design, but I expected it. QC in the current, simple form can only the validity of a record if that record is present. And once the architecture type is selected, an architecture record is created. And it stays, even if the type gets changed later on. The reason for that is that I did not want an accidental change of the type to eradicate data in the architecture form. I still think that is the wiser choice. 

So the gist is: QC Rules for type-specific locus data either have this flaw (which surfaces rarely) or cannot be had.

**Comment by lbestock** [comment]
I am indeed a fan of destroying the material evidence, and so this makes sense.
