### ISSUE TITLE
locus photos: filemaker shows blank panel over UI after inserting an image (error type 1)

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1253]
This here is for the image container in locus photos. Much smaller todo list on my side:

- [x] change add_*_to_cache method to the deferred strategy

**Comment by urapadmin** [comment]
### recording 11.6.3 
- [ ] apply test scheme

**Comment by luizaogs** [comment]
Ok so this seems to be working, but when I first added an image I got a “stop current script?” window and clicked “yes” and got the following:

![5B019572-34C2-4F9A-83C4-8D0E7D8500DB](https://user-images.githubusercontent.com/67970402/141654287-4dcb3804-a271-485d-bd54-cb54d46a382a.png)

I think it happened when I was typing in the description field but I haven’t been able to provoke it again. Image was there with description once I quit FM and came back in.

**Comment by luizaogs** [comment]
Hmm when looking up images in the gallery using their descriptions three of them showed up as they should (with both LA and LA-001), but the first one I added is only appearing under LA-001. Actually ok it shows up if I search for LA in the gallery but LA doesn’t show up as an identifier:

![8AAE3562-13EB-4B01-910A-E61E7728DBD0](https://user-images.githubusercontent.com/67970402/141654618-d733f37e-584d-46a8-bdc3-4b91bdca539c.png)

![780B0981-A5D8-47A6-9758-14F68B3B35F1](https://user-images.githubusercontent.com/67970402/141654654-88bc97c9-55cc-4140-9db1-4c7f16fe160b.png)

**Comment by luizaogs** [comment]
Everything else is working.

**Comment by luizaogs** [comment]
Oh wait, just for the record: when adding an image in the popup (not through the gallery) I get the keyboard flashing for a split second in between flickers but it goes away by itself (similarly to the menu appearing in #1251).

**Comment by urapadmin** [comment]
> 
> 
> Ok so this seems to be working, but when I first added an image I got a “stop current script?” window and clicked “yes” and got the following:
> 
> ![5B019572-34C2-4F9A-83C4-8D0E7D8500DB](https://user-images.githubusercontent.com/67970402/141654287-4dcb3804-a271-485d-bd54-cb54d46a382a.png)
> 
> I think it happened when I was typing in the description field but I haven’t been able to provoke it again. Image was there with description once I quit FM and came back in.
> 
> Ok it has happened again but I am unable to reproduce it reliably. It seems to happen when I click on the screen while/right before or after flickering. I did discover that if I click on “no” when it asks if I want to stop the script I don’t get the crazy window.

okay, that is bad. I have seen it, too, but in former versions. And yes, clicking on "no" is what you need to do because otherwise you not only get the stupid window you also interrupt the code at some undefined point and the operation it was processing is not finished. Result: Undetermined. Is it possible that you can most easily provoke it when you try to hit it exactly when the delayed flicker would occur? That's timed about a second after the image got inserted. And this happens definitely within the code that got delayed.

**Comment by urapadmin** [comment]
Is it possible, that the missing identifier above is the result of having interrupted that process, so when you got the white data window? That would make a lot of sense and we could forget about the missing identifier.

**Comment by luizaogs** [comment]
Huh, I was trying to reproduce the above weirdness and hit another bit of weirdness: I added a locus image and tried to add another but I keep getting image containers BELOW the image I had just inserted, instead of where they should be which is above that already inserted image. This is what the screen looks like currently: 

![IMG_0235](https://user-images.githubusercontent.com/67970402/141665497-81d99a81-ca9b-449b-8021-8c60443e084b.PNG)

It seems like the image container/image is somehow selected because the space around it is black/darker than the usual gray (see below): 

![IMG_EC3C91A9970C-1](https://user-images.githubusercontent.com/67970402/141665522-682f18a9-87e5-431e-a2c1-944b502d6c55.jpeg)

Leaving the context and coming back did not help, and neither did logging out and back in. Hm...

But even after clicking outside of the container and getting that usual gray color, if I try adding another image that empty container appears below this initial one.

**Comment by luizaogs** [comment]
> Is it possible, that the missing identifier above is the result of having interrupted that process, so when you got the white data window? That would make a lot of sense and we could forget about the missing identifier.

I currently can't provoke it at all any longer, but yes that's totally possible because I first got that screen when I inserted that exact image. But since I am unable to reproduce it reliably I have been unable to check this by trying to do it again.

**Comment by luizaogs** [comment]
Ok, wait. Got it again! Yes, that screen appears if I click on it about a second after the image was inserted. But in this case the image has both the locus and unit identifiers in the gallery, only I didn't click "yes" so the script wasn't interrupted. Let us see if I can do it again...

Ah interesting, this time I clicked "yes" and now the image itself doesn't appear at all. Hmpf. I just want to know if the gallery identifier issue is related to this but for that I need an image to appear, and I got the screen three more times but the images are not showing up if I interrupt the script as they did the first time I ran across this issue.

Ok, well, I can confirm at least that the script interrupted thing can indeed affect how things appear in the gallery because a new issue surfaces: I added another locus image, got the screen after I clicked during a flicker. I added the image description "Argh" but that does not bring up anything in the gallery.

![IMG_0237](https://user-images.githubusercontent.com/67970402/141665896-f13067bc-bbf9-40ac-b579-f5995fccb2f3.PNG)

![IMG_0238](https://user-images.githubusercontent.com/67970402/141665898-89855ab4-0f1a-4bc5-b8ff-d1bbc654c2f9.PNG)

Once I added to that description (it is now Argh????) it did show up: 

![IMG_816E882F6BF2-1](https://user-images.githubusercontent.com/67970402/141665916-16c82fd0-ce4f-43d1-a07c-66ec951e6651.jpeg)

**Comment by luizaogs** [comment]
(Just for clarification, since I wasn’t sure if your comment in #1250 was in reference to this. This is definitely not an error type 1, though if I hit that script screen after provoking it as described above I do need to leave FM and return for it to disappear. I am using the new 9th gen iPad and on FM Go 19.3.1.23, database 11.6.3)

**Comment by urapadmin** [comment]
> 
> 
> (Just for clarification, since I wasn’t sure if your comment in #1250 was in reference to this. This is definitely not an error type 1, though if I hit that script screen after provoking it as described above I do need to leave FM and return for it to disappear. I am using the new 9th gen iPad and on FM Go 19.3.1.23, database 11.6.3)

yes, I understand that. This is a totally different thing and filemaker is not unresponsive it is just that you can't get back to the original UI in this case here.

**Comment by urapadmin** [comment]
### @test 11.6.6
after all those years I learned that users always have the right to interrupt a script by default. I have applied the suggested measure to prevent that default to all cache-related scripts, so it should be solved here and in all the other cases you have mentioned.

**Comment by luizaogs** [comment]
I can still provoke it with mad clicking on the screen, but it is much harder now that it was before. So not sure if you can do anything else about it...

![IMG_0240](https://user-images.githubusercontent.com/67970402/141695389-207701bd-97e3-4620-968c-6376ae31d454.PNG)

**Comment by luizaogs** [comment]
Oh wait, but if I click on "yes" I no longer get the screen. Is that the fix you meant?

**Comment by urapadmin** [comment]
no. You aren't supposed to get the message at all. BUT it is possible that your mad clicking has interrupted a different script (there are hundreds) and that just does not lead to the open strange window. You interrupted something else. It can be but isn't necessarily damaging. I will look around what other script you could possibly have interrupted there. 

But it sounds like we are at least already at the point where only sheer madness and hardly accident leads to this?

**Comment by luizaogs** [comment]
Yes, it is mad clicking.

**Comment by urapadmin** [comment]
This ticket got a bit fuzzy with this interruption thing (which in fact could have happened in any other context, it is not local to locus images). So I would like to transfer the interruption to a new ticket (#1264) and ask you to focus here on testing the container without mad clicking and then let off your clicking steam in the other ticket.

**Comment by urapadmin** [comment]
So, with the next update I will look into the issue that new photos don't appear where they should. And then I will ask you to start all over again with this one. The test results are too inflicted by the script interruption error.

**Comment by urapadmin** [comment]
### @test 11.6.15 
Latest image container technique applied to locus photos, so a complete new test is necessary.
- [ ] I cannot reproduce the issue that new empty containers are not appearing where they should. At least not on Windows. Is that still an issue (without the interruption thing!)?
- [ ] Please test again thoroughly and don't forget that changing the description ALSO changes the file identifier cache, which is only visible when you go to the gallery and look at the image in the popup.

**Comment by luizaogs** [comment]
Just to make sure, the image description of the image in the popup (in the gallery) should only appear under the locus identifier rather than under both locus and unit, right?

![IMG_0257](https://user-images.githubusercontent.com/67970402/147107037-6add7187-e34e-4a59-afc3-274a4fd3b8a1.PNG)

**Comment by luizaogs** [comment]
Popups are missing the "insert image or file" text here.

**Comment by luizaogs** [comment]
> * I cannot reproduce the issue that new empty containers are not appearing where they should. At least not on Windows. Is that still an issue (without the interruption thing!)?

No, I think it was due to the script interruption. Haven't had it at all so far.

**Comment by luizaogs** [comment]
This is more flickery than other containers I've tested recently, I think, but other than that I've had no problems.

**Comment by urapadmin** [comment]
> Just to make sure, the image description of the image in the popup (in the gallery) should only appear under the locus identifier rather than under both locus and unit, right?
> 
> ![IMG_0257](https://user-images.githubusercontent.com/67970402/147107037-6add7187-e34e-4a59-afc3-274a4fd3b8a1.PNG)

yes, at least this is correct: It belongs to the most specific identifier, which is the one of the record type you had inserted the image into.

**Comment by urapadmin** [comment]
> This is more flickery than other containers I've tested recently, I think, but other than that I've had no problems.

hm. It does work with a 1 second delay but so do almost all of them. Only site maps has one not delayed version. I have looked at it but I can't find a difference. Is it reliably more flickering?

**Comment by urapadmin** [comment]
### @test 11.6.16
- [ ] "insert image or file" now there

**Comment by mcornacchia25** [comment]
I don't know if it's more or less than usual, but I reliably get 3 flashes inserting into both the primary and popup containers as well as when I change the description. Only 1 flash when deleting either an image or the container it's held in with the description. 

When I replaced the first image in a list of 3, the last one (or most recently created) is half scrolled down. It doesn't fix itself when scrolling on the same page.

![IMG_2B3A91E61026-1](https://user-images.githubusercontent.com/96021337/147281129-fb71e38e-9da9-49e6-baa3-b1b50b9fad39.jpeg)

Clicking onto another page and back fixed it though. 

Otherwise, everything seems to be working ok.

**Comment by urapadmin** [comment]
wow, filemaker has always something new in stock. It never cheers me up. This one I had not seen so far. This looks like half an error 1b. Does scrolling through the list rectify it?

**Comment by urapadmin** [comment]
> I don't know if it's more or less than usual, but I reliably get 3 flashes inserting into both the primary and popup containers as well as when I change the description. Only 1 flash when deleting either an image or the container it's held in with the description.
> 
Is that the case with, say dayplans or with site notes, too (locus relations are different)? Or is this here in locus photos from your perspective more flickering, too? Normally I would want you to get exactly one delayed flash.

**Comment by mcornacchia25** [comment]
Tried again and it seemed like

Inserting photo to dayplan: 2 flashes
Inserting photo to context/locus: 3 flashes
Inserting photo to relation: 1 flash
Don't know if this is relevant but changing the relation context or type flashes the code/spreadsheet thing and then flashes white.

**Comment by luizaogs** [comment]
To add to Meghan's last comment above, which matches what I'm getting for dayplans and locus photos, site notes have 1 flicker so it does seem like locus photos have more than usual.

**Comment by luizaogs** [comment]
I tried and was unable to provoke the error Meghan reported above when replacing an image in a list of 3 so that doesn't seem to be consistent across different devices.

**Comment by urapadmin** [comment]
> Tried again and it seemed like
> 
> Inserting photo to dayplan: 2 flashes Inserting photo to context/locus: 3 flashes Inserting photo to relation: 1 flash Don't know if this is relevant but changing the relation context or type flashes the code/spreadsheet thing and then flashes white.
Filemaker is pretty much like a crime scene, Meghan, every little information can turn out to be relevant at some point, so just keep mentioning what ever strikes you as helpful.

**Comment by lbestock** [comment]
Whoops. Trying this simultaneously on two ipads. First part of the test was just inserting into primary image container with no jingle bells and I'm already running into trouble. 
(First, I am getting three flickers too, but wow they are fast flickers compared to the flickers of November. Or was it October.)

Blipad is on iOS 15.1, FM Go 19.4.1.31
Flickering but no other real problem yet. I do not that when I created a second image container the screen stayed with the previously created image. The new image container was there, but I had to scroll to get to it. No other weirdness.

ldb_ipad on iOS 15.1, FM Go 19.4.2.202
First image container created and a classic 2a.
Second image no problems. I feel like I'm in California. But not really.

**Comment by lbestock** [comment]
And more fun.
I tried Meghan's replace the first image in a series of three trick. On blipad it worked just fine. On ldb_ipad it most certainly did not, **all three** image containers turned into total 2as, not Meghan's half a 2a and not for just one of the images. I have to leave the tab and come back to get them on again.

So that really is back to the frustration of four iPads returning three results.

The iPad currently known as ldb_ipad is my brand new mini 6th generation which should be the fastest of them all I think? But Luiza's is new and Meghan's is old so, yeah.

**Comment by urapadmin** [comment]
I will look into this again. I would have expected the least trouble with this one. 
In the meantime you guys could finish testing #1249.

**Comment by lbestock** [comment]
One last note for you on this one before I hit #1249, also familiar:
I remembered that as my primary ipad, ldb_ipad undoubtedly had 47 zillion apps running. I closed all but FM Go and repeated my steps exactly. Neither the original 2a nor the triple 2a after replacement occurred.

Please, god, it will be a cheap American wall that you bash your head against when next you hate Filemaker and not a proper stone German construction. Better for your head and much else.

**Comment by urapadmin** [comment]
### @test 11.6.17
We have to test this again because of a bug I found. There should be exactly ONE flicker and all should work, of course.

**Comment by mcornacchia25** [comment]
I'm getting 3 flashes when adding a photo or changing the description. Otherwise, everything seems to be working.

**Comment by urapadmin** [comment]
please make sure you are on the correct release. I just rolled 11.6.17 out and I think you were a bit too quick.

**Comment by mcornacchia25** [comment]
On the correct release and it is now working with one flash.

**Comment by luizaogs** [comment]
All working here for me, too.

**Comment by lbestock** [comment]
All working for me, too.

**Comment by urapadmin** [comment]
### @test v11.6.18
I reopen this after changes I made because of #1293. 
This needs only a quick new test by one of you to see if it still does what it should. You can close it again if it looks okay.

**Comment by mcornacchia25** [comment]
Worked for me
