### ISSUE TITLE
site map: filemaker shows blank panel over UI after inserting an image (error type 1) (and error type list)

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1255]
this is for site map. 
- [x] change add_*_to_cache method to deferred strategy
- [x] look at differences between site config and site note -> map

**Comment by urapadmin** [comment]
### kiosk 11.6.3
- [ ] apply test scheme
- [ ] 
Be aware that a site map can be added either in the site config or in site map photos on the second tab.

**Comment by luizaogs** [comment]
I'm also getting the flashing menu here between flickers. I know you said you accept that, but I'm noting it since it's no longer occurring in #1251 and #1252, after you reduced the delay. This was in the site map images (not config).

**Comment by luizaogs** [comment]
Deleting images: 

I do not know if this is the way it's supposed to work because I'm bad with images and can't remember. So sorry in advance! But should deleting an image in the little FM menu (this one below) lead to it disappearing from the gallery? 

![IMG_0246](https://user-images.githubusercontent.com/67970402/141697594-8e27e454-920c-415b-addf-bd3093bc0e7d.PNG)

Because it currently does (and the gallery then has empty image containers, which you see below). If I use the "no map" delete button in the popup itself then the image remains in the gallery -- that's what happened to the image you see in the screenshot below without an identifier.

![IMG_0245](https://user-images.githubusercontent.com/67970402/141697630-a6de5f69-d521-47b6-9f72-f4442979bdc6.PNG)

Ah so I just tried the same deleting method in a dayplan (using the FM menu) and the image did not disappear from the gallery, so this seems wrong for site maps?

**Comment by luizaogs** [comment]
The rest of it is fine here. I applied the scheme to both the site map images in the first tab and the site config.

**Comment by urapadmin** [comment]
on which version have you had that?

**Comment by luizaogs** [comment]
11.6.6, FM 19.3.1.23, iOS 15.1

**Comment by urapadmin** [comment]
to answer your question: No. No action should make an image disappear from the gallery. Never and in no part of the app.
Except for one, that is accessible only to special users: In the gallery itself when you click on the details button where you see the identifiers and the egg-button, there is a delete button that actually deletes an image from the gallery for good. It is more or less an option only for testers and developers.

**Comment by urapadmin** [comment]
We SO need to get away from filemaker. 

The bug about deleting a site map took me several hours and it makes no sense. Worked perfectly fine on fm desktop to begin with. But on fm go I must jump to the long site id otherwise the image container behaves different than the desktop version of filemaker. And it makes NO sense whatsoever to jump there. So this is another contingent hack to sidestep erratic fm go reactions. 
Who knows how long and how often that hack will work?!? 

I tested this with an older database, we have had this issue for a while, I guess, without really noticing it. So it slipped in with some filemaker workstation in the past. Wow. I am not happy.

### recording 11.6.7
- [ ] fixed? How can I call this fixed? Poked? Prodded?

**Comment by urapadmin** [comment]
before I release this: Please try Filemaker Go 15.4, which just got released and speaks of an improved compatibility with iOS 15. I future we won't label bugs bugs, we will label them compatibility issue.

**Comment by urapadmin** [comment]
not necessary anymore: Problem remains in FM GO 19.4

**Comment by urapadmin** [comment]
###@test recording 11.6.8 
Now that it is clear that this will be yet another bug in Filemaker that will never get fixed, my experiments lead to a version of the same hack that I can apply to the other containers with the same error as well:
- [ ] deleting should work now without side effects of any sort and the result should be as expected: image remains in gallery with identifiers gone

**Comment by lbestock** [comment]
It half works but not fully and I need now to do a structured test to figure out what is up. One can make or delete a site map either through a site note (index card) or a site creation (gear) entry. I am sometimes but not always getting the image deleted from the gallery and I will now test for you which combination leads to what - I get the feeling it is a pattern but I have just been poking and am not sure yet.

**Comment by lbestock** [comment]
Black iPad, 11.6.8 running on iOS 15.1, FM Go 19.4.1.31
Using a fresh database every time I have added and deleted site maps that sometimes are removed from the gallery still but not always. In each case I created a new site in a new database and added a new site map image from within the creation of the site (which I had done by clicking in the gear). So the thing I have not tested yet is if a site is made but not given an image, and then the image is added later through the site notes. 

Entered site note by index card; clicked on image, used menu to delete. GONE from gallery.
Entered site by gear; clicked on image, used menu to delete. STILL THERE in gallery.
Entered site note by index card; clicked on pop-up menu, clicked on image and used menu to delete. STILL THERE in gallery.
Entered site note by gear, clicked on pop-up, clicked on image and used menu to delete, GONE from gallery.

Shall I try what happens if I make the site map image through the site note index card entry? Not sure if that would help so I will hold off until you tell me to.

**Comment by lbestock** [comment]
Testing the same thing on my own iPad.
First two deletions same effects.
Third I made the site image as usual but hit a 1 error (if that is the one where it is temporarily not there, and I leave the tab (not FM) and come back and then see my image). But the deletion through popup worked as before, where the image is still there in the gallery.
Fourth, yup I get the number 1 error again. On the first flicker my image is visible, after the second the container is blank. I exit the tab and go back in and the image is as it should be. When I go through the gear and the pop-up and delete the image it is gone from the gallery again.

So: the deletion to gallery pattern was consistent across the two iPads. When the image is gone from the gallery, the image container still seems to be there as a blank. The image creation was different on the ipads; my own twice returned a number 1 error. If it is a number 1 error. I cannot currently find the bloody list of errors.

In a Kantian sense, I want to bash my head against a wall.

Needless to say that I had opened a number of apps in the meantime on my iPad and forgot to close them. But I had updated FM Go to be the same as the test on the Black iPad.

**Comment by luizaogs** [comment]
(I think this is the 2a error, not 1?)

**Comment by urapadmin** [comment]
okay, sorry. I am far from my best and should have told you that I have applied the hack ONLY to the immediate site map image container you get when entering through the gear. I just don't want to do things over and over in several places only to find out it doesn't work. 

So please rewind to 11.6.8 and start a fresh test again only using that one image container. No popup, no going through site notes.

**Comment by urapadmin** [comment]
Here is the list of error types again:

1 -    blank screen - that's the worst. FM (and not only the image container) is covered by white with things still happening underneath the white sheet (we know that from the menu that pops up). Although I think I might have seen reports suggesting the opposite I would say this is temporary. **ONLY** When **CLOSING FM** (not switching to a different app) and going back the white sheet is gone and the image there. 

1b - Same as 1a but it is enough to switch to a different app and back to filemaker to have access to the UI again. IT IS NOT ENOUGH for both type 1 errors to switch to a different part within the filemaker app (most of the time you are not even able to try).

2 - blank container. Here the image does not immediately appear in the container it was inserted into. This comes in two variations:

 2a. temporary: the image is there after leaving the form and going back. So the image has been inserted but isn't displayed at times. Usually it suffices to click on the header of the form or leave the current form and come back or switch tab panels to refresh the screen. Then the images reappears.

 2b. permanent: the image isn't there, even after leaving filemaker (something that so far only Luiza seems to be encountering). So it seems the image really has not even been inserted (the most mysterious of all of them).

3 - blank list: the other images in a list (we have seen that only in dayplans) turn to white - that only happens temporarily, so when leaving FM and going back they are there (so we know they have been inserted just sometimes they are not displayed).

**Comment by lbestock** [comment]
No errors of any sort to misnumber this morning on testing the part you have actually changed. Works.

**Comment by lbestock** [comment]
(Was slightly nervous the pinning would not survive closing the ticket, but it did. So maybe I will stop misnumbering errors going forward.)

**Comment by urapadmin** [comment]
not so fast. @luizaogs: Would you please test this again, too? Before I apply this hack to all the other containers I need both of you to confirm it is good now.

**Comment by luizaogs** [comment]
Yes, the deletion worked as it should.

**Comment by urapadmin** [comment]
I close this and start a new one under
