### ISSUE TITLE
transferring features from one block to another in URAP

### ISSUE THREAD

**Issue by Christian-Uronarti** [urapadmin/kiosk#1262]
Hi, 
is there an elegant way to transfer rooms/features created (mistakenly) in one block to another block?
C

**Comment by urapadmin** [comment]
Not even an unelegant way, because I suspect that would change numbering, right? 
Can you elaborate?

**Comment by Christian-Uronarti** [comment]
Yeh, DH created a series of around 20? rooms/features in Block III instead of Blocks ix and x based on info from Dunham's intro... he was wrong.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by urapadmin** [comment]
an example, please. I need a room that is now wrong and the info what would need to change and where it would belong. I‘ll have a look at it then.

**Comment by Christian-Uronarti** [comment]
Sure, Block iii rooms 97-104 and 121-126

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Christian-Uronarti** [comment]
Rest of info in next mail

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by Christian-Uronarti** [comment]
room 97 in block 3 gas the following data. The room is actually in block IX so the record in block 3 needs to be scrubbed and the information transferred to block IX

[cid:ebdaa179-b571-4ba1-963f-62efb8ee24ed]
[cid:2c2212a2-4f4e-426d-9c96-dac6a0be5ec7]
________________________________

**Comment by urapadmin** [comment]
@Christian-Uronarti: Please, please, log in to github itself (there is even an app and you can click on a link in the mails you get from github) and reply there. Or at least cut off the trailing earlier conversation when you reply be email, because this gets all cluttered and I can't see the relevant information in here anymore. 

So:
- Sure, Block iii rooms 97-104 and 121-126
- room 97 in block 3 gas the following data. The room is actually in block IX so the record in block 3 needs to be scrubbed and the information transferred to block IX

What are those cids? Are they numbers from the database?
[cid:ebdaa179-b571-4ba1-963f-62efb8ee24ed]
[cid:2c2212a2-4f4e-426d-9c96-dac6a0be5ec7]

**Comment by Christian-Uronarti** [comment]
sure, no problems. Here is the example: room 97 has been set up as a feature mistakenly in Block III (image 1) and has the following data (image 2 and 3). The room is actually in block IX so the record in block III needs to be scrubbed and the information transferred to block IX. The same goes for  98-104 (all block IX) and 121-126 (all block X). Those codes in the last mail were image files that didn't send for whatever reason. Does that make sense?

![image](https://user-images.githubusercontent.com/84924268/142049011-96e2d97b-1c7c-4cda-884a-4502b3926e20.png)

![image](https://user-images.githubusercontent.com/84924268/142049075-d5c8d930-08a8-4cf2-a70c-6b802c2657e6.png)

![image](https://user-images.githubusercontent.com/84924268/142049130-073263c6-51bb-4a8a-bb92-be75b1b606a7.png)

**Comment by urapadmin** [comment]
much better. yes, all clear and I'll have a look at it right away.

**Comment by urapadmin** [comment]
okay. That's an easy one. You can do that yourself.
- see the little red round buttons in the feature list of the unit? That cuts the relation between the unit and the feature. So that's your "scrubbing" part in Block III
- then you go to the other Block IX to the feature list and use the button that looks like a chain. That establishes a relationship to an existing feature. So you click that, select Room 97 and Bob's your uncle.

**Comment by urapadmin** [comment]
Oh, and by the way: You can do it the other way around, too. The feature has a tab "recorded in" where you can cut the connection to the unit and then add the relation to a different one with the same chain button.

**Comment by urapadmin** [comment]
can we close this?

**Comment by urapadmin** [comment]
I close this.
