### ISSUE TITLE
field manager / sync manager: use vite instead of webpack

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1266]
I hate webpack. So we try to use vite here in future.

**Comment by urapadmin** [comment]
since I started this I have to finish it for #1156

**Comment by urapadmin** [comment]
### @test 0.13.13
The field manager should simply behave normally in all regards

**Comment by urapadmin** [comment]
not there: After I cancelled forking I got a misaligned button and worse I cannot click on it:
![image](https://user-images.githubusercontent.com/38838314/144227167-a1098d33-9db7-4f0c-8e4c-3f39befc8286.png)

**Comment by urapadmin** [comment]
@test 0.13.14
Now it should be fine. 
- [ ] The issue above occured e.g. if you force an error by importing a wrong fm database or just cancelling a running process
- [ ] please test all options you can think of in the sync manager since the transfer to vite has more or less touched every single part of it!

**Comment by luizaogs** [comment]
Hmm, I started preparing a database (Luiza-isms) and canceled the process to see if I could provoke the error. I didn't get the error, but I have been since unable to prepare it at all -- it keeps telling me that exporting to FM has been canceled by a user but I only canceled it the first time around (yes, I did clear the cache).

Preparing databases in general seems to be taking longer than usual, and it's not my internet so not sure if something is up with that. Ok in fact no, it seems to be stuck at 1% (this is Luiza's Mac). Yep, then it told me that exporting to FM had been canceled by a user and I never tried canceling that one at all.

**Comment by luizaogs** [comment]
<img width="1512" alt="Screen Shot 2021-12-11 at 10 05 26 PM" src="https://user-images.githubusercontent.com/67970402/145699836-84b0e91c-28a2-43fa-a193-f6e679a5e1ad.png">

**Comment by urapadmin** [comment]
little server disruption due to Brown's user account muddle. It should be over.

**Comment by urapadmin** [comment]
but at least this was a very good occasion to see the button and press it. It seems that worked, didn't it?

**Comment by luizaogs** [comment]
Ah. Thanks, Brown. The button does work. Let me look at the rest...

**Comment by urapadmin** [comment]
shouldn't you be on your way to Brazil?

**Comment by luizaogs** [comment]
I got here this morning and got tired of doing nothing very quickly so now here we are.

This is all working - I tried everything, including group operations.

**Comment by urapadmin** [comment]
Are there monkeys? Is there winter?

**Comment by luizaogs** [comment]
There is definitely no winter. There might be monkeys - if so I shall send pictures :)
