### ISSUE TITLE
new configuration option: delay_cache_operation_style

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1275]
### @test recording 11.6.10
This can be tested AFTER the image containers seem okay and so it is for ipads only:
set admin/delay_cache_operation_style to "delay": This uses a somewhat different technique to defer the cache operation that kindled the filemaker bug for so long. 

Test, if the image containers are still working properly or if you start getting error types 1 again. I suggest to use an image container that had been most prone to produce type 1 errors.

**Comment by lbestock** [comment]
Once we've closed #1249 let's test this one in locus relations.

**Comment by luizaogs** [comment]
Should we test this one yet, or are we waiting for #1278 to be closed?

**Comment by luizaogs** [comment]
I thought I would test this since #1278 seems ok now. I got no 1s.

Fyi though, the instructions for this setting in admin say to set it to "pause" rather than "delay" as you mention above. I tried it with both since I wasn't sure which one was correct, but it might be worth clarifying the instructions in FM depending on what the correct one is (or if both work, I suppose).

**Comment by urapadmin** [comment]
I think I will do away with this option, anyway, and stick with the delay strategy (in fact I totally forgot about this). It is all already complicated enough. So, don't worry about this.
