### ISSUE TITLE
image gallery: sorted by modification date in descending order

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#1292]
### @test 11.6.17
I thought that might help the testing. The gallery is now sorted in a way that the most recently modified images should appear on top and the oldest at the bottom. Scrolling through miles of images on an ipad isn't fun.

**Comment by luizaogs** [comment]
Oh thank god (it's working).

**Comment by luizaogs** [comment]
Hm, interesting -- I'm deleting image records to test other stuff and just wanted to note here that if I delete the image itself from the dayplan it moves up in the image gallery list because it was modified, but if I delete the dayplan (with the trash can) it doesn't move in the gallery list. I guess because the dayplan record was modified, not the image? This seemed to make sense to me but I thought I would check.

**Comment by urapadmin** [comment]
hm. No, in fact those two things are in the end really the same. Deleting an image from a container should not change its modification date. So the Trash can does the right thing and the fm menu does not. Only adding an image or replacing it should change its modification date and move it up the gallery.

But honestly, reaching coherence on that front might be beyond my patience. Let's leave it open for a while.

**Comment by luizaogs** [comment]
Ah ok, well this is the case for every container I've been testing. Fyi!
