### ISSUE TITLE
password setup differs for new and pre-existing users

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1317]
I am not sure if this is a bug or a hangover from a change in how password setup works, but it strikes me that it would be less confusing if it is the same for everyone. (Also this might already be a ticket? But I couldn't find it.)

Resetting the password for preexisting users by clicking "must change password" in editing a user does not currently work (0.13.15). It does work still for new users. I have created new users and clicked that button and I get the expected dialog to create a password when I try to log in. 

I am able to reset the password for a preexisting user by clicking "reset password" in the list of users on the landing page for admin in kiosk. That works the same way for pre-existing and new users.

**Comment by urapadmin** [comment]
It is neither, I think. It is just a different design than you expect. 

- "must change password" does not reset a password and is not meant to do so. It is meant to force the user to change the current password to a new one. It works for both new and existing users the same. If it is not doing that, please file a ticket for that one bug.

- New users don't get a password on creation (unless you give them one afterwards with the button on the admin landing page). I cannot give you the opportunity to do so in the dialog where you enter the new user data because I am using a standard tool for all of these admin tables.

- The button on the admin landing page does the same for new and existing users (in fact it only deals with existing users for once you add a user that on exists).

So in the end you have all opportunities you want. You can either add new users with empty passwords or add them and apply a random password right after adding them. For the admin area that's as comfortable as it gets.

**Comment by lbestock** [comment]
Aha, I misunderstood "must change password". Works as you expect it to.
