### ISSUE TITLE
file picking with "all" set to dummies did not work

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1321]
I had the following file picking rules defined for the file picking recording group. From my understanding this should have turned everything to dummies, no? It didn't. Once I changed "all" to "contextuals" in the 2nd order rule it worked as it should.

<img width="1512" alt="Screen Shot 2022-01-23 at 11 09 27 AM" src="https://user-images.githubusercontent.com/67970402/150682751-97237c4b-8afc-4ade-9dbd-6d1753df97c3.png">

**Comment by urapadmin** [comment]
### @test kiosk 0.14
that is a lack in documentation. Applying the "ALL" rule anywhere but on the lowest order makes no sense because the rules on the lower orders would be always irrelevant. That is why "ALL" is only processed as the low order rule. The latter leading to complications because it acts as if it were the lowest order rule (being overridden by what has explicitly set as the lowest order rule). To get out of that muddle I have 
- [ ] clarified in the documentation that "ALL" is only effective as the first order rule
- [ ] ignore an "ALL" rule completely (including a warning in the logs) if it occurs anywhere but as lowest order rule.
