### ISSUE TITLE
unsuccessful workstation import

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#1324]
Was trying to add some data to test the director's view for #903 and got the error in the screenshot below. But I definitely opened and made records in the database, and also closed it properly. Could it have anything to do with being behind the server's timezone? I have mine set to Chicago GMT time, but I know Laurel tested this in California a while back and it worked so hm.

<img width="1512" alt="Screen Shot 2022-01-25 at 9 40 47 PM" src="https://user-images.githubusercontent.com/67970402/151100420-5ab6c1a3-401f-49bc-bf49-2f982f81367a.png">

**Comment by urapadmin** [comment]
ja, that‘s interesting. Please don‘t do anything before I had the chance to look into it tomorrow.

**Comment by urapadmin** [comment]
I add @lbestock @mcornacchia25 so that you all know. It is helpful for me if you click the "show more details" button in such a case and make a screenshot that captures the log entries that precede the red entries (well all you can get on a single screenshot will do) and the red entries themselves. 
@luizaogs I found the log for this one, so no need to repeat it or so. Just a little help for me in the future.

**Comment by urapadmin** [comment]
for the time being I'd ask you to test with a different workstation and leave this one alone. I analyze the evidence later in the day. First: 🧀->🛒

**Comment by urapadmin** [comment]
well, I can at least confirm that the "has_been_opened" marker of the uploaded database is set to False. So that has not been set when working in the filemaker database.

**Comment by urapadmin** [comment]
frankly, I am really at a loss here. If you have logged in to the database and saw the start page, the "has_been_opened" marker should have been set. This is not bound to any condition, so it has nothing to do with timezones or anything. 
So the only thing that I can imagine would be that you opened the database but did not log in or that you thought you were in the right database but you were in fact in a different database (e.g. because you have not closed a former one in filemaker). 
If nothing of that is possible then it is a mystery to me.

**Comment by urapadmin** [comment]
so that you can carry on, just open your database, log in, close it again and upload it again. That should solve the issue at hand. And then should we call it a hiccup?

**Comment by luizaogs** [comment]
Oh my god it had been so long since I uploaded an iPad database and I was so tired last night that I forgot to send the database from FM to files before uploading. Yikes. The good news is that everything worked with the newish timezone setting, so yay?

**Comment by urapadmin** [comment]
yay 🎈
