### ISSUE TITLE
back arrow from locus photos goes to dayplans

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#1326]
11.6.23b on Laurel's iPad.
When one makes a context photo and then hits the back arrow in the upper left corner, one should go back to the list of contexts. But instead it tells me to please wait and then takes me back to the dayplan/narrative tab instead.
This does not happen if one is in the photos tab but does not make a new photo.

Aha wait - it's making the description after taking a photo that is the problem.
If I just take a photo but don't describe it, the back arrow gets me back to contexts.
If I just make a description but don't take the photo, the back arrow gets me back to contexts.
But if there is a photo in the image container, whether I just took it, or took it before and left the description blank and then left the tab and reentered, then adding a description makes it so that the back arrow takes me to dayplans/narratives instead of to the list of contexts. 

So the problem comes in adding a description to an image where the image is already there. (And it happens the same way if I change an existing description.)

**Comment by urapadmin** [comment]
ja. This is really a timing problem. That's where the cat bites its own tail. By delaying the operation that is kindled when changing the description, part of the refresh happens when the locus form is already closed and the excavating form is visible. 

### @test 11.6.25
I have now tried to make this impossible by "disabling" (I wish something like that were possible in filemaker) the exit button and the arrow keys and plus button. When you try to click on them the change of the description will be performed and then they are enabled again and do what they are supposed to do. That is not perfect user experience but keeps strange errors away at least.

Should this work for you I will introduce it at least in collected material, too. Introducing it everywhere would just kill me right now.

**Comment by urapadmin** [comment]
@luizaogs: I add you here. You are faster than Laurel :o)

**Comment by luizaogs** [comment]
Yes, this is working for me. No strange errors any longer, and I don't think having to click on the arrow twice is a big problem -- the color change and the "please wait" panel make it clear that something is going on and it's not just a weird lag, I think.

Not sure if I should close it yet so I won't.

**Comment by urapadmin** [comment]
no, let's wait for Laurel to close it. She brought it up. But it seems I did not introduce a new bug here, at least.

**Comment by lbestock** [comment]
The button color change particularly helps. Works.
