### ISSUE TITLE
leaving out images during fork

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#15]
While leaving out data seems a huge issue (and isn't really the point), leaving out images for certain Workstations might make more sense. Why not leave out all images before a certain date or include only images for a certain site? What makes most sense from an excavation perspective? leaving out by SITE.
Or: For specialists it might make sense to leave all images but collected material and/or ceramic images

**Comment by urapadmin** [comment]
The forking could be more workstation and workstation-type specific. Some workstations might not want certain data. That would allow for smaller filemaker databases, if we can limit a filemaker database to a certain site or a set of units.

**Comment by urapadmin** [comment]
connected to #14

**Comment by urapadmin** [comment]
### @test kiosk >= 0.10.0 and recording system >= 10.3
Currently the user interface to test this is a temporary solution. In the end this will happen somewhere on workstation level in the workstation manager. But for the time being the test has to use the war rules. The rules are described in the developer's manual: 
[https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:file_picking](https://www.meritaten.net/urapdev/doku.php?id=manuals:developer_manual:file_picking)
The workstation type must be filemakerworkstation and the recording group should be default for the first tests. The available resolutions are "high", "low" and "dummy", the latter for omitting a file entirely.

**Comment by lbestock** [comment]
I have to think about how to test this. L&L discussed it. At this stage, test by coming up with an idea of what you want to see/not see and then write rules to include and exclude that get you there. Not necessary to test file container types differently. <> is "not equal to" and will be difficult! X is yet to come but will make a difference to some of the issues we have already run into where an image was a dummy when it was expected it would be real (because it was in another context where it was a dummy). X will mean "is exclusive to". LKH will either make a file resolution "tiny" or change "low" to be visibly pixilated so that we can test that low/high are differentiated properly, not just dummy/present.

**Comment by lbestock** [comment]
This can be closed. File picking exists and works. Separate tickets for different operators and the like exist and will require work.
