### ISSUE TITLE
user hints if recording has gaps

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#31]
hints to users if information regarding a data entity is complete. So: collected material without description is not.

**Comment by urapadmin** [comment]
I would like to tackle that before arch1900 this year, if arch1900 will happen.

**Comment by lbestock** [comment]
Would we make it configurable as to which fields produce hints? Some fields are more relevant for some projects than others, and a worry here is fatigue with messages leading very quickly to ignoring them.

**Comment by urapadmin** [comment]
no, we would not. The idea is to have a set of rules to check (can be quite elaborate such stuff, close to a domain specific language). And my plan has always been to mark the form or whatever group of information suggests itself with an icon that is only visible if something stinks according to the rules. Clicking on it would reveal the issues. Users can click on it or ignore it. Of course, one could classify such rules according to priority and some might even be so severe that you are not allowed to procedd as a user (e.g. no unit id when creating a unit). 

The same set of rules can also work on the server side to help you in the directors view. 

But that's the wrong way of thinking about it. First I would want to know what we can possibly check. An experience I have always hoped to get out of the field, alas ....

**Comment by urapadmin** [comment]
Alex might be willing and able to tell you what the Troy system checks. Was it Troy?

**Comment by lbestock** [comment]
Pompeii :)

**Comment by lbestock** [comment]
I have emailed him.

**Comment by lbestock** [comment]
Hello Laurel,

You can get a glimpse of our required fields in the attached screenshots; Brief Description ("Summarize the SU"), Opening date (autofilled), Photograph, Long description (cut off in the screenshot), and Type & SubType. The other information on the front page of each SU isn't absolutely required, largely because of the nature of our workflow (spatial data is collected by a separate team, the materials info on the left reflects where things are in our processing workflow, etc.). The required fields only block you from "closing" a context, so it is unfortunately all too possible to leave a record incomplete forever. The only field that is really "required" is the opening photo, as the button obscures later steps. Some of the other essential info can be recovered later in our process (3d modelling every context makes elevations retrievable later), and the core of the excavation team has been working together since 2007 so we have a high degree of trust that the right things will get done.

As for College Hill, it seems our task is to keep students from starting to dig before the irretrievable info is lost, which to my mind would be opening photo and elevations (though I'd like to encourage Anna to 3d model everything too, as we have so few contexts over the course of a season). We definitely didn't get as many photos as I'd like, so that is a clear area for improvement. Our finds data seems like it can catch up from any entry deficiencies during the lab portion, though i would not at all be surprised if Anna's take on that is different. I'd like to force some more fields to be entered before closing (relationships, namely), and then instructors would just have to force students to actually close out contexts when they are finished.

Hope that helps, if I can clarify or go more in depth just let me know!

Best,
Alex

![image](https://user-images.githubusercontent.com/49291909/88484547-61dc3e80-cf3d-11ea-8ad6-614c4d5c84cc.png)
![image](https://user-images.githubusercontent.com/49291909/88484558-702a5a80-cf3d-11ea-8476-7088a97e93ea.png)

**Comment by urapadmin** [comment]
@lbestock This would be the next and last key feature I would want to tackle before June.

**Comment by urapadmin** [comment]
as for actual rules: #1042

**Comment by urapadmin** [comment]
while the filemaker implementation is done, the kiosk implementation is next.

**Comment by urapadmin** [comment]
meanwhile I documented quality control for users: [https://www.meritaten.net/urapdev/doku.php?id=manuals:user_manual:quality_control_for_admins](https://www.meritaten.net/urapdev/doku.php?id=manuals:user_manual:quality_control_for_admins).

**Comment by urapadmin** [comment]
and there we are: Integration in kiosk and integration in the director's view are there as a first try in 
### @test kiosk 0.11.5
- [ ] quality control rules are applied by kiosk during house-keeping, which runs as part of synchronization by default
- [ ] when using housekeeping in administration there is a new checkbox for quality control. You can switch all other options off and just that one on to get a run of the quality control engine only
- [ ] quality control rules and flags have an even more basic user interface than in filemaker in kiosk. Accessible when in administration as a new menu item in the burglar menu
- [ ] there are little round icons behind the locus identifier
- [ ] the icon has a color that reflects the most severe of the messages
- [ ] when clicking on the icon the messages for the locus are listed - again with coloured icons accoding to severity

**Comment by urapadmin** [comment]
there are a few things open concerning quality control in kiosk. I make new tickets for them:
- when changing context - file relations in the edit dialog of file repository quality control rules should be recalculated for the involved contexts
- when importing files via upload or local import qc rules need to be recalculated, too. 
- $$ variables are not sufficiently supported by kiosk, let alone configuration keys. But that is mostly an issue for #889
