### ISSUE TITLE
new locus types

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#390]
there was something about fill and deposit. Is a fill even something different? 
We also have a "grave".  What would be the fields for these types?

**Comment by lbestock** [comment]
Deposit
Fill (Yes, that's something different, that was the point, though in fact I would want to talk to them about it again because the difference is in its relationship to other contexts. It is essentially a subcategory of deposit in the way I use the term deposit. But its fields would not be different.)
Structure (same thing as our architecture, so same types of fields though they will not have bricks...)
Cut (Here the defining thing about it is what it cuts through. Again a locus relations issue. But the whole thing about a cut is that it is not there to describe, it is an absence.)
Grave (Fields we discussed were "individuals" with numbers. I would myself want each individual to be able to choose between primary/secondary, and intact/disturbed, and in Egypt I would want immediately to note the presence/absence of a coffin - that couldn't be done in collected material because more often than not my coffins are simply smudges in the sand and cannot be collected.)

These are changes that are better for us, too. We currently have "burial", "negative", and "cut" under "other" - negative and cut I am not sure I want to distinguish between, and they and grave (better than burial, I agree with Candace there - the burial is a locus within the grave) are on the same order as "deposit" so belong in the higher level. The question is if we want to keep "other". I think so. We need it for URAP for Wheeler stuff because that does not correspond to any of our types. It gives others greater flexibility.

**Comment by urapadmin** [comment]
Although widely misused that way, tickets should not be inner monologues and they should not replace discussions. I could answer now to your grave and then you would reject that again and in the end we were mimicking what github is full of. Developers writing discussion threads instead of code. These things should be discussed in a working meeting and your inner monologue is what you bring as notes. You can use the wiki, too. But I want to use github more concise: As precise directions about what the software should do but does not, currently, as possible. So, for instance, this very answer here is not what should be in here :o)

**Comment by urapadmin** [comment]
New label: Needs discussion. -> Means we need to talk about it.

**Comment by urapadmin** [comment]
that should be done now, right?

**Comment by lbestock** [comment]
Still missing "cut" as a locus type. (This is the same as #93 at this point.)
