### ISSUE TITLE
relations not implemented in feature unit

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#403]
in the tab "relations" in the feature form there whould be a list of units that are related to this feature.

**Comment by urapadmin** [comment]
### new in v9.3.1
 - [ ] The list should reflect exactly every unit where the feature had been added in the "features" tab at some point.
 - [ ] a button allows to link a survey or excavation/feature recording unit from within feature recording (it is not possible, currently, to jump to such a unit from within feature recording, though). 
 - [ ] it should not be possible to link any other unit type from here
 - [ ] a button allows to delete the link to such a unit
 - [ ] the list shows the unit type and recording method of that unit.

**Comment by lbestock** [comment]
This is a fun one to test and needs some attention. MJ, I'm giving it to you to test when we get to Day 2, afternoon. You should then think about how to design your surveying and feature making so that it hits all these points. I fully expect you to be confused and to use the ticket to ask questions when you're in the middle of it!

**Comment by myjaylee1123** [comment]
While I can't link an excavation trench, it looks like I can still link a feature with a unit that's another survey type. Is this okay, or is this an issue?
![IMG_0343](https://user-images.githubusercontent.com/47072505/88316181-64445b80-cce5-11ea-9488-f9cb6301dc7d.PNG)

**Comment by urapadmin** [comment]
yes, that's perfectly alright since features can be linked in all survey units. So it should be possible vice versa.
