### ISSUE TITLE
configuration move use_simple_excavating

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#429]
The hint is not sufficiently clear that one is changing only layout, not functions. Move to visibility.

**Comment by urapadmin** [comment]
you can do that yourself: Login as admin. Now you can access the help text (the one that once confused you) and the category. Choose a new category (and a new help text, perhaps) and after the next synchronization it will be the same everywhere. In fact that is the only way now, I cannot do that in the template, now that configuration is synchronized.

**Comment by lbestock** [comment]
? I do not see how to change either the category or the help text?

**Comment by lbestock** [comment]
This is a help text IN configuration itself - is that something I can configure? How? Currently "use_simple_excavating" is a yup/nope in "general configuration". Please teach me how to move "use_simple_excavating" to the "visibility" and how to change the hint for a configuration - all the configurable hints I see on the "help" part of configuration are for things one runs into in the recording itself.

**Comment by urapadmin** [comment]
Have you tried it being logged in as admin? BUT even if that works, you have to synchronize your changes and export a new recording system afterwards. And then I need to know so that I can transfer the change into the template. So in fact as long as we are juggling several projects in parallel (and you are talking a bout a change you'd want for all projects) it is better to just tell me what to change.

**Comment by lbestock** [comment]
Request: move the configuration setting "use simple excavating" from general configuration to visibility. 

But if I should be able to do that myself, and to change help texts that appear when one is in configuration (rather than just those that appear in recording) then in fact I'm not very satisfied asking you to do it for me and would like to be shown how to do that, too.

**Comment by urapadmin** [comment]
Done in the template v8.9.12. But the template configuration will be overridden by the current configuration in the respective database of the project. I have enabled the normal admin to change category and help-text now, so that you can change them, too. But that is a bit paradox because the category and the help text are meant FOR THE ADMIN and so the admin changing her own help texts, well, is a bit like talking to herself.

But: If you change something in the configuration that is meant to be permanent in all projects, it has to be done in all projects one by one.

Only if a project's database is emptied, the template configuration is used for initialization. You cannot change the template's settings. That is why I need to know about permanent changes of the configuration, as well. I am not sure, perhaps we need to talk it over to make you understand.

**Comment by lbestock** [comment]
At least the basic "how to change these things" part I understand so immediately that I discovered it myself in the latest version when I didn't have this ticket open, and knew what was up.

**Comment by lbestock** [comment]
Test:
When you're comfortable wiping USTP out, you'll do that. The test is to see if this change has been made in the development template, has been migrated to the USTP template, THAT template has not been overwritten by the configuration of the USTP testing, and there fore the move of use_simple_excavating to visibility (such a lot for such a small thing) is reflected in a newly produced USTP empty database from the USTP template.

**Comment by lbestock** [comment]
A wiped clean USTP 8.9.16 -use simple excavating is still in general, not visibility.

**Comment by urapadmin** [comment]
indeed, because I overwrote it again with the ustp config. I have to find a way to protect those attributes or this will be a never ending story.

**Comment by urapadmin** [comment]
I have an idea: #556. Once I have implemented that idea, we'll try again.

**Comment by urapadmin** [comment]
### v8.9.17 and kiosk 0.7.1 
well, I invented a somewhat odd mechanism that lets me override configuration keys for all projects. I used it for the said key "use_simple_excavating". When you download the first 8.9.17 Alice, it should greet you with "update successful". That tells you that my configuration keys have been applied to your workstation. In order for them to enter into your (ustp) project's master database you have to synchronize this one workstation (as the text tells you). Because if Sam downloads his workstation from the ustp server, his workstation does not get my configuration keys and his database will not say "successcully updated". After you synchronize yours the changes to "use_simple_excavating" will have entered the master database. If I prepare your workstation again, it should not again show the update successful message again but the changes to simple_excavating should still be there, namely that it appears in visibility. Voila.

**Comment by lbestock** [comment]
Done!
