### ISSUE TITLE
duplicate image dropped during sync - should be rewired instead

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#441]
currently if a user inserts the same image in two different places in the file repository, the only option to continue with synchronization is to drop those images. That is not satisfying, especially since there is no way for a normal user to find out which image has been dropped.
There are two solutions: 

1. Allow a redundant image as a new option (instead of dropping it).
2. rewire the image in the record. Since I know the image that is already in the file repository, I should be able to set it in place of the redundant one. This is the best but also the most complicated fix for the issue.

**Comment by urapadmin** [comment]
see also #701

**Comment by urapadmin** [comment]
2. is definitely the best solution. I will try that one first. If it gets overly complicated we fall back on 1. 
They cannot both be a solution because solution 2 can only be useful without having any redundant images in the database.

**Comment by urapadmin** [comment]
### @kiosk 0.8.27
done. I wish I could test it better because, going wrong, this could screw up a lot. It needs manual tests.

**Comment by lbestock** [comment]
I am not sure if I am testing this correctly. I just tried to put the same image in multiple places in the recording system and synchronize, expecting that this meant that only one image would be uploaded but a reference to it would exist in all the places I put it. Synchronization itself failed on the basis of duplicate images.
![image](https://user-images.githubusercontent.com/49291909/110176080-c9f6db00-7dd0-11eb-8541-ee686897c70e.png)

**Comment by urapadmin** [comment]
That is the old behaviour, so this is indeed a bug.

**Comment by urapadmin** [comment]
- [ ] dumb. I forgot to actually offer this new feature on the user interface. There is a check box now when starting synchronization that should be checked by default. If that is checked, files are being rewired.

**Comment by lbestock** [comment]
Works!

**Comment by lbestock** [comment]
Developer wishes more robust tests because this is a big one. So multiple workstations at the same time for instance. So test it on Beset, Luiza and Laurel both putting the same image in different containers, and then uploading and synchronizing. Luiza, let's use the PLG image from the gallery of an old playground. Put it lots of places! Keep track, and let's make sure it ends up in the contexts we both put it in after a synchronization round.

**Comment by luizaogs** [comment]
Wait, sorry, confused. Which image? Are the two of us using the same image?

**Comment by lbestock** [comment]
Yes, we both need to use the same image, keep track of where we put it, and then synchronize. I chose the PLG image because it is easy to find in the gallery and easy to pick out visually - it's a b/w photo of a playground from the 50s or some such. (The confusion might be because that later comment with the broken images was a different test, not using the PLG image. I was on the local server, not Beset, there.)

**Comment by luizaogs** [comment]
Oooh. I took the "old playground" to be an old filemaker playground, rather than an actual playground, so had no idea what you were talking about (silly). Ok, will do.

**Comment by luizaogs** [comment]
Oh wait, but you sent it back to Lutz so do we wait to do it?

**Comment by urapadmin** [comment]
I move this back to you guys, you seem to be on it still.

**Comment by luizaogs** [comment]
@lbestock -- let me know when you want to do this, then!

**Comment by lbestock** [comment]
It hasn't been wanting to do it that has been lacking...
BUT this morning I have some time. So let's both put an image in multiple places in PVD, upload, and synchronize. Let us think through this. How do we put the same image in multiple places? We both need to have that image first, separate from its existence in the recording system. The playground image is great but I will fee better if we use a new one. Check your email in five minutes...
Then we should respond here with which contexts we attach that image to so that we can check to make sure the links are all there properly.

**Comment by lbestock** [comment]
I put testing_image_1 in: Providence: PBA dayplan; PBA-001 locus photo; and PBA-004-4.
I put testing_image_2 in: Playground: 47 dayplan; F416 dayplans; and then back in Providence: LA dayplans since it is, after all, a gift for Luiza.

**Comment by luizaogs** [comment]
testing_image_1: Playground -- 58 dayplan; OStesttrench1-003 locus photo; F501 dayplan

testing_image_2: Providence -- LA-005-7; F410-1; PBA dayplans (that way we can have ice cream together).

**Comment by lbestock** [comment]
I want black raspberry, please.

**Comment by lbestock** [comment]
Oh that's an interesting import error you have received. I think I'll let the developer finish breakfast before we hit him with that one.

**Comment by luizaogs** [comment]
Worked perfectly! Is this enough of a test for this massive ticket?

**Comment by urapadmin** [comment]
I would not mind if you tested it in more than one record type, so at least in a locus and a collected material context.

**Comment by luizaogs** [comment]
We had dayplans, collected material, and locus images I think?

**Comment by urapadmin** [comment]
if that all worked, then you can close this, of course.

**Comment by urapadmin** [comment]
and now I get some milk shake for all the pain here

**Comment by luizaogs** [comment]
Very well deserved.
