### ISSUE TITLE
new handling of site note photos

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#472]
site note photos need the new image handling and caching.

**Comment by urapadmin** [comment]
### @test
Needs Version 8.9.4 or higher
site note photos

Always work with at least two site notes and always test the photo stuff in the second one. 

1. add a couple of new photos (not through the gallery) in the tab (instead of in the popup with the add from gallery button)
2. make sure that after adding the photos they can be found in the gallery when searching for the site's id
3. do the same thing but this time in the popup
4. add photos from the gallery and make sure afterwards that they can be found in the gallery under the site id (be careful to use images that didn't show up for this site to begin with)
5. delete a photo or two from a site note (and hence the site) (there is a remove image button in the popup)
6. make sure that the images are not any longer found in the gallery under the site id
7. delete a site note (instead of single site note photos) and make sure that all the site note photos that were attached to the site note cannot be found any longer in the gallery under the site's id.

**Comment by SamKimball-BrownU** [comment]
Issue 1: Only images that were inserted from gallery are searchable.


Issue 2: Deleting images has visual error, see below:

Before deleting the topmost image (note that it is blank)

![image](https://user-images.githubusercontent.com/61027113/76474749-f4d36c80-63d2-11ea-9a63-4c16b8eaaa56.png)


and after
![image](https://user-images.githubusercontent.com/61027113/76474775-09176980-63d3-11ea-8ceb-da3893848d0e.png)


Note that this does not mess up anything when searching in the gallery, but does mess up thumbnails and the popup images

**Comment by urapadmin** [comment]
as for 1. I can't really reproduce that. Site note photos were found by the site's short id (e.G. PLG for playground). Is it possible that you tried the long version? However, I have added the long site title to the cache so that a site note photo should be found in the gallery under that title if and only if you don't use the "strict" search mode.
fixed in v8.9.10

**Comment by urapadmin** [comment]
### v8.9.10
two should be fixed. Please test thoroughly, the changes might have different bad effects.

**Comment by SamKimball-BrownU** [comment]
USTP 1.9.11/Windows 10

**1.** The same behavior persists, here's a screenshot of the information in gallery of the newly uploaded site note photo
![image](https://user-images.githubusercontent.com/61027113/79056327-d7d0ca00-7c1a-11ea-9b09-b06ef1e62ca9.png)
Note that they do not appear when "site_note_photo" is selected in the bottom drop down in gallery search either.

Using Gallery to upload site note photos still works/is searchable.

Nothing shows up when searching by full site name when using strict mode, but images uploaded through gallery do show up when searching full site name when not using strict mode.

**When deleting the site note images that were added through gallery, they are also deleted everywhere else they are used.** When searching for it under identifiers that should be there (say from the dayplan, not the site note), a record pops up, but does not show the image. This seems like a good clue? See below. 

![image](https://user-images.githubusercontent.com/61027113/79056474-9ccf9600-7c1c-11ea-83eb-b442db98f195.png)
GAL3 is the image I deleted in the site note. It should still be here, but was deleted when I deleted the image in the site note.

![image](https://user-images.githubusercontent.com/61027113/79056487-bcff5500-7c1c-11ea-9faa-0ef746bfdff9.png)
This is what happens when you then search for GAL3. 

The correct behavior happens when searching for it under site note identifiers.

I think that this behavior is related to the behavior in #471, I would guess related to image handling in Site records as a whole

**2.** is resolved! Whoo!

**Comment by urapadmin** [comment]
The last error about deleting a site note does not seem to be related to the original ticket. I transfer that to its own ticket:

**Comment by urapadmin** [comment]
I still cannot reproduce this behaviour. Please send me a copy of the filemaker file that has the bug.

**Comment by SamKimball-BrownU** [comment]
I just emailed you the file :)

**Comment by urapadmin** [comment]
thanks. Unfortunately even with your file I can't reproduce it. Perhaps you are on a different filemaker version? see also #471

**Comment by urapadmin** [comment]
### fixed in 8.9.12
This is the second image container I have equipped with the new drag & drop handling. Please test it again competely.

**Comment by SamKimball-BrownU** [comment]
Issue 1: When images are added through the gallery, they are not given site identifier (and are thus not searchable)

Issue 2: Deleting images works visually, but does not delete identifiers. They remain searchable in the gallery.

Note: Drag & Drop seems to work perfectly for adding images, as intended. It gives a popup warning, but works properly in the database. Images added this way still suffer from issue 2, i.e. they can't be deleted properly

**Comment by urapadmin** [comment]
### v8.9.14: all issues here should be solved now

**Comment by SamKimball-BrownU** [comment]
Resolved except for known bug with drag and drop; however, the warning appears, so I think that this is good for now. Closed.

**Comment by urapadmin** [comment]
reopened because image proxy was not set correctly.

**Comment by urapadmin** [comment]
### v9.1
Filemaker is die Höchststrafe
