### ISSUE TITLE
simple excavating: change dayplan to new image handling

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#478]

**Comment by urapadmin** [comment]
### @test
We have two versions of the excavation layout: a simple one containing only dayplans and loci and the older more complex one containing lots and collected material as well. Dayplan images need to be tested in both layouts.

**Comment by lbestock** [comment]
For Sam to test: change between simple excavating layout and not as admin in configuration, general, "use_simple_excavating". Test dayplan images in both using the ordinary battery of image testing steps.

**Comment by SamKimball-BrownU** [comment]
Not-simple works perfectly (except issue #487 still persists with the backspace thing)

Simple also works fine, except a new issue was discovered that exists in both simple and non-simple dayplans. Submitted as a separate ticket, #521

I'm moving this into back to developer just to bring your attention to the new ticket, but otherwise resolved.

**Comment by urapadmin** [comment]
@test v8.9.14
Sorry, due to yet another change in strategy this has to be tested again.

**Comment by SamKimball-BrownU** [comment]
Simple and non-simple works. All other testing done in #487
