### ISSUE TITLE
update image container to new file handling in surveyor request

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#506]
unsure if that is even necessary

**Comment by urapadmin** [comment]
Alas, it was more than necessary. It is in fact one of the more tricky file containers:
### @test 8.9.18
  - adding an image to the image container will insert it first into the gallery without applying it to any context identifier. 
  - That is correct, because the connection to the dayplan happens only after hitting the big green ok button
  - Before hitting the ok button the image can be deleted. Unlike with other file containers, here the whole image record is deleted! So the image must be removed from the gallery! 
  - when hitting the delete button for the whole surveyor request the same thing must happen: The image is deleted entirely from the gallery.

**Comment by lbestock** [comment]
Sam, you can learn surveyor requests on this one! My guess is that you're not going to find them documented anywhere sufficiently to do it without asking, but that will at least expose holes.

**Comment by SamKimball-BrownU** [comment]
Issue 1: once surveyor request is fulfilled, the image is not actually added to the respective dayplan. It has all the right tags in the image gallery, but it just does not appear in the dayplans.

Issue 2: when inserting into popup via right click, this error appears. Happens whether in admin or non-admin account

![image](https://user-images.githubusercontent.com/61027113/82092460-f6fdc400-96be-11ea-86c1-4e7c4fc180e8.png)

File maker has to then be force closed in task manager. Similar thing happens when drag and drop is used in popup, but in that case filemaker does not actually freeze.

Impossible to test deletion/etc until issue 1 resolved

**Comment by urapadmin** [comment]
### fixed v9.0.6

**Comment by urapadmin** [comment]
reopened because image proxy was not set correctly.

**Comment by urapadmin** [comment]
### v9.1
Funny. Here the image proxy would not have been set at all.
