### ISSUE TITLE
deleting site map with trashcan in tab site_map does not work

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#524]
originally a part of ticket #471:
"However, deleting it using the trash can (not in popup) does not remove it from searches"

**Comment by urapadmin** [comment]
fixed in v8.9.12

**Comment by SamKimball-BrownU** [comment]
Now it does not work using any method of deletion :(

**Comment by urapadmin** [comment]
again, unfortunately I cannot reproduce this in you current workstation file. I tried all variations again: gear -> without popup, gear with popup, clipboard with popup and without. All delete the file identifier cache entry correctly. There must be something different about your data. Please send me your database (as for #530).

**Comment by SamKimball-BrownU** [comment]
AHA!!!!!!!!!!!

SO I think I misdiagnosed the problem, in that it is not a problem with the file identifiers/etc. but rather with the image search/what is cached there.

It was reproducible UNTIL I did this:
1. Log in as admin
2. turn on testing mode
3. open up file cache developer menu

THEN everything started working as intended!

**Comment by SamKimball-BrownU** [comment]
SO:
the way to reproduce the bug on my file:

1. go into SAM
2. create new site note
3. add new site note photo
4. search in image gallery to confirm that it was added correctly, search for SAM
5. (this was always working as intended up to here)
6. Go back and delete site note using pop-up/trashcan
7. Use **Image gallery**
8. you need to refresh searches if you are using the same image gallery from the home page, enter in just a single letter or delete SAM and press enter (it remembers you searching SAM from last time, this isn't a thing in other image galleries I don't think)
9. search for SAM again, and the site note photo should appear under the search (very bottom because it was newest entry).

WORKAROUND:
USE admin login!!
I don't think turning on testing mode is actually necessary for the workaround

But basically I think either my configuration for sgk is wacky or there is problem with admin privileges or something

**Comment by SamKimball-BrownU** [comment]
note: logging in with admin resolves basically every new issue that I have had

**Comment by urapadmin** [comment]
### v8.9.14: all issues here should be solved now

**Comment by SamKimball-BrownU** [comment]
Resolved. My previous testing notes are a bit messy so I checked site note for this issue too, and it is all good there.
