### ISSUE TITLE
erroneous error messages when attempting to create a locus relation 

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#598]
![image](https://user-images.githubusercontent.com/49291909/80928603-917f0e80-8d73-11ea-8cc8-860bdc20bd21.png)
Alice, KHPP, 9.
Went to locus relations. Created a new locus relation. Attempted to input "to locus". Got the proper drop down menu of available loci, clicked TE2-001, produced this error message.

Clicked OK and got the following error message:
![image](https://user-images.githubusercontent.com/49291909/80928638-d145f600-8d73-11ea-84d9-3f75f1586f67.png)

Clicked oh, ok, and then lo and behold the proper "to locus" had been input into the field. But I think you still want to know about it.

**Comment by lbestock** [comment]
Did not happen with the second locus relationship in the same locus, the difference in my order of operations being that in the second one I defined the type before defining the locus.

**Comment by urapadmin** [comment]
bloody image containers

**Comment by urapadmin** [comment]
I cannot solve this situation perfectly due to filemaker insufficiencies. But the common use case should be covered and the messages should not appear anymore. One thing I can't change for sure is that one could go select something for type and locus and then go back to type and hit del or cut to do away with the type. That can result in a mess.
