### ISSUE TITLE
Deleting of Dayplans in feature recording - need suppress backspace & delete

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#615]
The exact same thing is happening as in #536 , but this time in feature recording

The same solution should work here, just suppressing backspace and delete keys.

Must be hell, not being able to reuse code....

**Comment by SamKimball-BrownU** [comment]
Also happens in survey units

**Comment by urapadmin** [comment]
Well, there is code reusing in filemaker but no way to reuse ui elements. There it is all copy & paste. And that is why you find me fixing an error in one place and not in another one. As a development environment Filemaker is stuck in the 1990 - at best. Good that I am from the 70s.

However, **fixed in 9.0.4** in both forms. Hopefully.

**Comment by SamKimball-BrownU** [comment]
resolved
