### ISSUE TITLE
khpp server so consistently upset I think something is wrong

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#619]
For the second day in a row I am running into constant problems with the khpp server getting stuck and being unable to calculate searches in the file repository. I am on the ustp server at the same time (both 0.7.2) and the exact same requests there work in light speed (ie "locus relation photos"). I never seem to have to click in the upper left corner for USTP, and for KHPP it more often than not does not result in actually resetting things to where the search works. I then close the browser window and open a new one and still not responding. (I never seem to have any trouble getting to workstations, or getting to the file repository. The pain comes when asking it to search in the file repository. And it is not always, and not consistent, as in there is no search that always fails nor any search that always works that I have discovered yet.)

**Comment by urapadmin** [comment]
I have changed to web server configuration so that it matches ustp exactly. Khpp should be as responsive as ustp. If this has an effect we can only observe, so please try and try again.

But there is also a slight issue that might have played into it. If you use an identifier that does not exist you get the red dotted frame around the identifier but the "calculating..." stays (although calculation is done). As soon as the identifier is correct everything works fine. It is harder to see if you type an unknown identifier and then play around with other things like record type or so. As long as the identifier is not correct, the "calculating..." does not go away, no matter what else you do. I make that a new ticket and leave this here to observe the general stability issue.

**Comment by lbestock** [comment]
This appears to be fixed.

**Comment by urapadmin** [comment]
I have had it again... It went away again, too, but ...

**Comment by urapadmin** [comment]
I close this here and we wait what the experiences with the current server software are.
