### ISSUE TITLE
field "recorded by" also available on locus/context observations tab

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#648]
Currently we have the excavator as a field at the unit level and at the narrative. For USTP in particular it is wanted on the locus/context level. I would not at all mind having it for URAP and suspect it would bother no one so you can just put it there, not make it customizable. See also #646.

**Comment by urapadmin** [comment]
and what about collected material? The other idea was to just **s h o w** the user on creation in general in all records. It is record anyhow (well, it isn't but I would make it do that).
See #389. 
So: No selection at all. The only downside is giving the ipad to somebody else while being logged in.

**Comment by lbestock** [comment]
And then that would automatically update if modified by, like in the file repository, too?
But I like it. No selection at all. Records and shows whoever was logged in when the record was made. Including on CM. Default label (I like theirs better) is "recorded by" and then I'm not even sure it needs to be configurable? It is always capturing who did the recording is all.

**Comment by urapadmin** [comment]
ok, new plan: we make a "recorded by" (and I will make that term customizable) in narratives (where we already have it), excavation loci, collected material and small finds. 
I make the "modified by / date" visible almost everywhere but that field cannot be changed.

**Comment by urapadmin** [comment]
we decided to show a "recorded by" field in:

- [ ] excavation: narrative (excavation and simple excavation), but here without the label
- [ ] excavation: locus tab down below the locus list and only visible if recorded by is actually set for the locus!
- [ ] edit locus: on the first tab
- [ ]

**Comment by SamKimball-BrownU** [comment]
I'm really confused on what the actual intended behavior is here. Are you talking about the field at, for example, the top of a new narrative, next to the time stamp?

![image](https://user-images.githubusercontent.com/61027113/87486837-caecb980-c601-11ea-993f-b726a192361d.png)

In the case of the loci, when there is one defined, it'll pop up with a little green 

![image](https://user-images.githubusercontent.com/61027113/87487183-99c0b900-c602-11ea-9b6f-7591e8a9cbed.png)


Or do you want me to test the configuration of label_recorded_by... in which case it always just remains "recorded by" in the software, no matter how I change it in configuration

I don't know, I'm a bit lost on this one. Sorry for taking so long to get to this, by the way.

**Comment by urapadmin** [comment]
No surprises. In part you are confused because you found the first bug. 
We have done two things: we have invented those little labels which show the modification date and user. They are almost everywhere and are covered by #389. The modification date and user is recorded automatically.

In some forms we also record who __created__ an information and when. That is what we call recorded_by. It is not always recorded automatically and it is also not always labeled "recorded_by". Now comes the list:

- [ ] the term "recorded_by" can be changed with the configuration key labels\label_recorded_by. The configured term should appear wherever the record_by field has a label.
- [ ] excavation: narrative (excavation and simple excavation). Date and user were already here before, that's why you see a difference. No label here. I have listed it here for completeness.
- [ ] excavation: locus tab down below the locus list and only visible if recorded by is actually set for the locus (see next check box)! Here you found your first bug: If you have changed the label it should not say "recorded by" but whatever you configured it to be. 
- [ ] edit locus: on the first tab. Here you find a recorded by label and input field. It controls the label mentioned above.
- [ ] collected material/small finds: what was formerly "registrar" is now "recorded by" (and should obey your configured label). The field itself was already there.

So in fact most of the time the field already existed and only the labeling has changed. I hope it's a bit clearer now.

**Comment by SamKimball-BrownU** [comment]
So this is what I changed in configuration, I changed it to "noted by"

![image](https://user-images.githubusercontent.com/61027113/88320027-9dc79780-cce2-11ea-8372-9214806793da.png)


issue: configuration doesn't change the term in excavation locus tab down below the locus list (third checkbox)

![image](https://user-images.githubusercontent.com/61027113/88319914-71ac1680-cce2-11ea-8a1f-21811bc58c01.png)


Narrative works as before, seems good to me?

edit locus tab: configuration still didn't change the label for recorded by

![image](https://user-images.githubusercontent.com/61027113/88319899-6bb63580-cce2-11ea-80b3-24461bf3e2ba.png)

small finds label is also not configurable, although it has changed to recorded by.

![image](https://user-images.githubusercontent.com/61027113/88320194-d7000780-cce2-11ea-88fe-a8c3d840813b.png)

This was all in simple, I shall change configuration to non-simple excavating and try all the tests again

**Comment by SamKimball-BrownU** [comment]
All the same problems exist in non-simple excavating

**Comment by urapadmin** [comment]
### v9.4.2
next try

**Comment by SamKimball-BrownU** [comment]
Everything is working! Nice.
