### ISSUE TITLE
tag feature and survey units

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#664]
by tagging those units types what in fact gets tagged is the invisible locus. This is a temporary solution until we have unit tagging in general. It allows to connect the collected material that's attached to a feature or survey unit with the cm attached to loci.

**Comment by urapadmin** [comment]
see also #663

**Comment by urapadmin** [comment]
### v9.2.2
- [ ] There is an interpretation tab now in features like the one in loci.
- [ ] one can add tags to the feature
- [ ] one can add an interpretation
- [ ] when in tag analysis the (usually invisible) locus and the collected material of the tagged feature shows up.

**Comment by luizaogs** [comment]
Testing this currently. I did find the tag analysis tab (I know, I'm surprised too), but am not sure it looks exactly as you might want it to so I thought I would check before closing the ticket. 

![image](https://user-images.githubusercontent.com/67970402/88442572-04cc7580-cde3-11ea-9ce9-8bbb4c02d337.png)

Starting from the initial tag analysis screen (screenshot above). The collected material tab looks great to me. The photographs tab includes all photographs from the tagged context (LA-006) and those of collected material from the features and survey units (no photographs of the unit or features themselves). As you can see, nothing shows up for "context type" or "description" for either the survey units or the features on that initial screen. Which I guess makes sense since neither are actually contexts? But it looks a bit odd to me, since it seems like there is information missing. 

If one then clicks on the record for a feature from tag analysis, the interpretation stuff and the collected material are all there but observations/descriptions and photos are not. They are of course there in the original feature record. The same applies for survey units (the photos and interpretation appear but not any of the notes or photographs). "Context type" on that window is marked as "hidden," which indeed suggests to me that nothing is supposed to be shown for context on that initial tab of the tag analysis (see screenshot 1). The actual tagged context (in this case LA-006) looks fine with all tabs filled out.

I suspect this is how it is meant to look since you only mention wanting collected material to show up above, but since I wasn't sure I am here crowding your inbox once more. I have left the two check boxes that relate to this empty of checks for now, but if you tell me this is all as it should be I will check them and close the ticket.

**Comment by urapadmin** [comment]
more of a real issue is that one can click on the edit button here and got to the locus. That mustn't happen since it is an invisible locus. That IS a bug. 

The other observations are indeed correct and lead to a bit of confusion. I consider showing something like "does not apply" or "-" or something that at least looks intentional.

**Comment by luizaogs** [comment]
Got it. I think adding either "does not apply" or "-" would be helpful!

**Comment by urapadmin** [comment]
### 9.4.4
It is a bit borderline here. In the end this was invented as locus tagging and the feature locus tagging is a bit weird in here. 
So I stop listing those features under "locus" at all. They are no loci. But their images will be listed in photos and their collected materials will be under collected material. That is still not optimal, I suppose. But for 9.5 it is at least coherent.

**Comment by lbestock** [comment]
I suspect it will get a sort of a scenario workout because multiple people have asked for the ability to give relations between features in somewhat the same way as loci. It can't be done archaeologically in the same way as loci; the types of relationships are not really the same. But tags there might work - it is one of the few remaining cases where I see a use of tagging still in the field and thus in the recording system instead of in analysis.

**Comment by urapadmin** [comment]
fine, make it a new request when the requirements are a bit clearer. To me it looks a bit like a special thing coming out of this unusual test excavating scenario. Definitely nothing that needs priority.

**Comment by luizaogs** [comment]
Ok so only the actual tagged loci show up in the locus list now, but for collected materials and collected material photographs we are only getting stuff from the loci and the features, not the survey units. You only mention wanting collected material from the features in your comment on the 9.4.4 update above but the original checklist mentions that collected material for survey units should also show up so just checking!

(I do agree that having features and survey units in the list of loci is confusing but now one can't see everything grouped under that tag and that's a bit difficult to track, no? Is there a list of everything under a certain tag? I missed this when I was trying to figure out if I had forgotten to tag the survey unit in the first place and whether that was why the collected materials weren't showing up, so it might be a desire very much tied to the testing itself but I think being able to visualize that would be useful? Though I don't really understand what tag analysis is used for at the moment so take that with a grain of salt. I see that you have something called "define tags" -- maybe even just a list in there? Don't know.)

**Comment by urapadmin** [comment]
The thing in brackets would be a new ticket for laurel to discuss. Please make one if you think it worth the while.

**Comment by urapadmin** [comment]
collected material from survey should appear as well.

**Comment by luizaogs** [comment]
Not currently. Survey unit 40 is tagged and has collected material but that does not show up, while the stuff from the locus and features do: 

![image](https://user-images.githubusercontent.com/67970402/88665297-ca016080-d0b4-11ea-9509-32b7c44eb712.png)
![image](https://user-images.githubusercontent.com/67970402/88665305-cc63ba80-d0b4-11ea-972f-678785155298.png)
![image](https://user-images.githubusercontent.com/67970402/88665311-cec61480-d0b4-11ea-82b5-3dd69fc5dee4.png)

The images of collected material from unit 40 aren't showing up either.

**Comment by luizaogs** [comment]
@lbestock -- does my comment above about listing the tagged stuff seem actually relevant for how you use this? I don't want to start a useless ticket if it's irrelevant!

**Comment by urapadmin** [comment]
We must be doing different things. Can you please delete and select the nightstand tag again in tag analysis? All I can think of right away is that you saw the last analysis results from before the survey unit got the tag and they did not get recalculated on entering the tag analysis form again. 

![image](https://user-images.githubusercontent.com/38838314/88668832-6c383d00-d0e3-11ea-9799-91f66b366b7d.png)

**Comment by luizaogs** [comment]
Ooh it doesn't update automatically? Yes, you're right. I'll close this and if Laurel wants the other ticket open that one later.

**Comment by lbestock** [comment]
Don't worry about another ticket currently. The case of a tag having both loci and features assigned to it is extremely test-case. The issue of how to group features and if tags are the way to do that (and therefore what a list should look like with a tag of only features) is separate and discussed in a different ticket.

**Comment by lbestock** [comment]
I remembered incorrectly; it is not a test case scenario at all to have loci and features tagged together - that is the essence of Wheeler Rooms as features. (And blocks are survey units, so also relevant here.) So whether or not this solution works (not technically, I mean works archaeologically for analysis) needs to be tested with the URAP data by Laurel. And my guess is that I will want to see the feature and survey information, not just the collected material, etc.

Scenario testing is hitting use of tags for grouping features in non-excavation settings, so with no loci. In that case it will certainly be weird and we will definitely immediately decide we need to see descriptions, etc. But I'm not sure that is quite the same issue; Lutz discusses the desire to be able to tag everything and it will come. For the time being I suspect I will ask that we simply turn back on the ability to see features and survey units in that list of contexts (and then perhaps rename the list) - tagging as it already exists is so useful and can help us do these things we in fact want to do now, as a happy accidental benefit of the hidden locus solution.

Laurel, attend to this after the next team meeting on 4 VIII 20.

**Comment by urapadmin** [comment]
please start a new ticket and don't reopen what is already a monster.
