### ISSUE TITLE
erroneous error message on download

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#668]
![image](https://user-images.githubusercontent.com/49291909/86424490-b549cc80-bcb0-11ea-86ea-852919c91145.png)

Kiosk (jolly jobber) told me there was a problem on download. But in fact (as you can see at the bottom left) the download ran just fine and I was then able to open the file.

(and I don't know what to tag it. We just talked about remembering to tag. And this is kiosk, but the only kiosk tag says "related to the whole shebang" and I don't know that this is? I leave it untagged but remembered to assign myself...

**Comment by lbestock** [comment]
Hm though I think you have created a self-assign bot for me...

**Comment by urapadmin** [comment]
I created a self-assigning bot for everybody. Whenever somebody adds/edits an issue or adds/edits a comment in an issue the bot goes off and adds that author as assignee. 
As for the bug: That's one of those things that happen every once in a while because web development sucks due to its basic design and idea. Sending little byte packets around the world, after they have been even split and sent in different directions and expected to arrive in a jumbled order, well, isn't all that reliable. "Try again" is what mostly helps. (Nonetheless keep recording such hickups).

**Comment by urapadmin** [comment]
Don't worry about labels except for one: "filemaker" and that is clearly not the case here.

**Comment by urapadmin** [comment]
this is obsolete because we have the field manager now.
