### ISSUE TITLE
use a new color for feature units

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#672]
the header and lists / tab control headers should show a special color for features for easy distinction between the feature form and other unit forms.

**Comment by urapadmin** [comment]
### recording 9.2.2
We use this color for features:
![image](https://user-images.githubusercontent.com/38838314/86501272-b6a1f480-bd97-11ea-9af6-35bdbe42a286.png)

It should show 
- [ ] in the header of feature recording
- [ ] in the tab header and background of the feature list in excavation unit with method "feature recording"
- [ ] in the tab header and background of the feature list in survey units

**Comment by SamKimball-BrownU** [comment]
ok issue: there are two different shades that are used. I'm colorblind, particularly in this shade of greens, but it is clearly different. Here it is in the excavation/feature recording:

![image](https://user-images.githubusercontent.com/61027113/88336255-49c8ad00-ccfa-11ea-944e-2ae87b2ac64d.png)

and here it is in survey features

![image](https://user-images.githubusercontent.com/61027113/88336282-577e3280-ccfa-11ea-962c-5547461d1704.png)

and here's the header in a feature unit

![image](https://user-images.githubusercontent.com/61027113/88336350-741a6a80-ccfa-11ea-870d-92e1ff78b443.png)


So the excavation/feature recording is different than the other two, because it's a couple shades lighter.

**Comment by urapadmin** [comment]
Sorry for totally ignoring all kinds of, uhm, handicasps (is thaz PC in English?).

But that aside it looks ok to me. Features are kinda turquoise excavation units are Uronarti-Green. If there is a tab with a list of  feature units it is turquoise (loci are orange). That‘s the idea. 
Am I missing something?

**Comment by SamKimball-BrownU** [comment]
![image](https://user-images.githubusercontent.com/61027113/88337917-26533180-ccfd-11ea-9a6b-6b1c254f15ef.png)

Here's a comparison between the two tones. The one on the left is the turquoise in excavation/feature recording, the one on the right is the turquoise that is in survey features and feature units. They are certainly both turquoise, but not the same shade of it? if that makes sense, one is much darker than the other. Something I am almost certain would not be noticed by a user, but since I am focused in on this one particular feature, I figured I'd point it out. 

But, given that one has black text and the other has white text, maybe this is intentional?

Disability is usually preferred to handicap in english, just because of the connotations that come along with it. Luckily, with stuff like this, I can use color pickers/etc to tell the difference, which is probably why I noticed this particular difference.

**Comment by urapadmin** [comment]
Ha. You clearly turned what PC calls a disability (I have my problems with thinking that term to be an improvement) into an ability. I did not pay attention to that difference in color. I will attend to it,

**Comment by urapadmin** [comment]
### 9.4.4
fixed.

**Comment by SamKimball-BrownU** [comment]
This particular issue is resolved. I'm making a new ticket with regards to the text color, #784
