### ISSUE TITLE
unit selection dialog box will not close

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#675]
Test drive of URAP 9.3 on Laurel's mac. I selected site: fortress, and then clicked on the menu by unit to select a unit. I got the  whole list, as I should. But I do not want to select a fortress unit in fact, so I went to close the dialog box by clicking the X in the upper left corner.
![image](https://user-images.githubusercontent.com/49291909/86515588-05777a80-bde8-11ea-9fa8-e7ab3b8b4d7e.png)
It does not close the dialog box. It flashes red when I click, registering my click, but does not perform the operation. I can close it by selecting a unit.

**Comment by urapadmin** [comment]
because that is not an x to close the list. That x deletes the filter input field.

**Comment by urapadmin** [comment]
oops, didn't want to close it. But in fact it is closed. You will object that this is misleading, but we use this icon everywhere in the system where a selection needs to be cleared, so ... here it is just somewhat misleading because the field is the only one and that's why the button ends up in the upper right corner.

**Comment by lbestock** [comment]
I don't mind the button itself or its function, it's just that I also want a way to get out of the box if I don't want to select a unit.

**Comment by urapadmin** [comment]
click anywhere else. It is a normal popup as with images or even the former list.
