### ISSUE TITLE
link existing feature to survey and excavation / feature recording

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#679]
currently it is only possible to add a new feature. What if there is already a feature and we just want to link it? 
That needs a new button and a feature selection.

**Comment by urapadmin** [comment]
- [ ] feature selection (should of course only show features)
- [ ] link by selecting one of them

**Comment by lbestock** [comment]
Some of these you'll notice need to be tested in ways that require making more records, and deleting them, than you would do in our PVD2020 scenario testing. 

Let's talk about the best way to do this. You don't want to confuse your actual data recording, you do want to do it while your head is in the recording. This could mean using a different database entirely, not PVD2020, that you trash after playing with rather than uploading. The problems there are that you have to make sure you're using an up to date version, and that you're not as in it mentally. Another option would be to use the PVD file to test these issues AFTER you have uploaded your actual data, before you have downloaded the synchronized new one. What would seem least confusing to you?

**Comment by myjaylee1123** [comment]
It be best to test these issues AFTER uploading the actual data so I don't eh mess it up

**Comment by urapadmin** [comment]
can we close this?
