### ISSUE TITLE
cannot download file from kiosk

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#686]
Luiza can get kiosk to prepare the file, but not to download it. She gets stuck at this screen:
![image](https://user-images.githubusercontent.com/49291909/86822750-04e61a80-c05a-11ea-9b60-bf269bfe6655.png)
And cannot push the black button. Nor can she push the "other options" button. The problem occurs in Safari and Chrome on her iPad.

We almost certainly figured this out, but are using it to demonstrate ticketing. The problem: ancient iPad. Luiza remembers that you had problems with it in Petra. Software version 10.something and it thinks it's up to date...

**Comment by urapadmin** [comment]
I am a bit puzzled that you were able to press the buttons to prepare the file but pressing the button for a download does not work. That might give me a clue as to how I could possibly support such an ancient Browser. There is a hack to at least download the file:
if you type this as an address (while being logged in to kiosk:
https://test.arch-kiosk.brown.edu/workstationmanagercontroller/ws_download/<workstation-id>/start with <workstation-id> being the workstation id that has been used to create your workstation (I suppose that was Laurel, so she would know. Otherwise I can look it up). But I have a hunch that you won't be able to upload it either and there is no hack for that.
Before we dive a bit deeper into this: Can you install Filemaker Go 18 at all? Because if you can't, the ipad cannot be used.

**Comment by lbestock** [comment]
The workstation ID is logsipad. With the initial letter being a lowercase L, not an uppercase I.

**Comment by urapadmin** [comment]
so the url would be https://test.arch-kiosk.brown.edu/workstationmanagercontroller/ws_download/logsipad/start. Tried it, works at least on a pc.

**Comment by luizaogs** [comment]
Nope, no Filemaker 18 so I have appropriated my mom's iPad -- which is not so ancient and so can deal with Filemaker 18. See other ticket for the next Luiza issue (you'll be getting a lot of these, I think).
