### ISSUE TITLE
TouchDraw - What is correct way of exporting images?

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#689]
So, to get the dayplan from touchdraw to filemaker, I exported the image to the camera roll and then inserted it as a normal image. Is this the "correct" workflow?

**Comment by urapadmin** [comment]
I invented and added the users-manual tag. That's all I have to contribute here. The idea is to use it for tagging issues that should be handled by a user manual of sorts.

**Comment by lbestock** [comment]
It is definitely how I would have done it myself!  And so can be the basis of instructions given in the user manual. Though I would also say that any way that works is "correct".

**Comment by urapadmin** [comment]
As a general remark, an officially correct way, or a "best practice" helps all users. Think of the many ways of organizing the download and transfer to filemaker. They all work but user's clearly need guidance because some ways of doing it are more prone to mistakes than othres. I state that "wrong" is not the opposite of "correct" :-) But if words trigger reflexes I propose "best practice" as a ways out.
