### ISSUE TITLE
Carry info from collected material tab to small find? Particularly, weight

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#698]
Upon using the software to make a small find, I found that I entered the weight on collected material, and then again on the small find tab. Would be nice (mostly for consistency's sake) to have that information carry over. Again, not so much for convenience, but more to make sure there isn't any conflicting info

**Comment by lbestock** [comment]
It's an interesting case, and let's think about it, because the two forms are really filled in at different times and by different people, and generally we try to avoid redundancy at all. Collected material is to be filled in by the excavator on bagging and tagging something. It is a field record, necessary so that an object or bag has a number from the start and can be tracked. Small finds records are made by the registrar at the house when doing a detailed examination of an object. Now, an excavator cannot ever weigh something in the field - we don't have scales out there. Weighing is done at the house. So why have weight in both places at all? Well because sometimes there are things that are not small finds that need weighing, like a sample, or on some projects a bag of ceramics. In that case the weigher might also not be the registrar but another specialist. Would that specialist be going in through the registration interface? So in fact we have here a bit of a muddle of workflow/personnel that results in a redundancy in the recording system. Is Sam's idea that they be linked so that the most recently entered weight in either goes in both the best solution?

I suspect we've had long discussions about this before, but I don't remember their outcome.

Lutz I'd be curious how this got used in the last URAP season, if there are ever different weights for the same URAP#, how often weight for CM was used at all, who was putting weight in (ever Lyndelle?)

**Comment by urapadmin** [comment]
I suggest we use one field (collected material weight) and show it in both places. I cannot imagine a case where there is a DIFFERENT weight in cm than in small find. Can you?

**Comment by lbestock** [comment]
I cannot. That seems a good solution.

**Comment by urapadmin** [comment]
### 9.4.1
done. Weight in small finds is the same as in collected material now.

**Comment by SamKimball-BrownU** [comment]
This is a reminder to myself to test this when I'm going through the archaeological scenario

**Comment by SamKimball-BrownU** [comment]
Actually cannot test this right now because we're only on 9.4. oops.

**Comment by SamKimball-BrownU** [comment]
Fully functional as far as I can tell. Works both ways.
