### ISSUE TITLE
test server for PVD gets stuck

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#700]
Add this to the load of issues such as #619. Beset is beset with troubles.

All members of PVD came back from the field and uploaded (surprisingly without issue, despite my deliberate failure to tell them how to do it and the fact that a handful of them are not iPad people). 

I did the imports.

I did the synchronization.

Lovely, looks good in File Repository, Sam made a zillion images and everyone seems to be getting Touchdraw without too much difficulty, also surprising. Kids. 

I prepared Alice, forked and exported no problem.

Immediately after I moved on to prepare Black iPad. Nope. I refresh. I log out and in again. It just spins. It spins at initializing, when I hang on. Eventually it gets to the 0% 0% fork and export screen. Then it goes nowhere at fork. Most recently I am still hanging on, not even getting to fork.

Please figure it out! I can't work!

Oh hey wait this time it actually told me it failed forking. Usually it just doesn't do anything. Here is my message:

![image](https://user-images.githubusercontent.com/49291909/87097486-5dace300-c213-11ea-8858-cd5336d4a2fb.png)

**Comment by lbestock** [comment]
Super weird - when I clicked out of that it refreshes the page and says now that the Black iPad IS prepared for download?

**Comment by lbestock** [comment]
And then the Green iPad ran smoothly, one click, fast, done.

**Comment by urapadmin** [comment]
Okay, one of those hiccups that will never entirely go away since they are circumstantial, network-related, not repeatable, worst nightmare for developers because it like with the quantum. If you look at the bug it is already elsewhere. So most important here is for users, particularly admins, to stay calm and not make things worse with hasty action. 
1. "nope" is not a description that helps me understand. I suspect the first issue was the black ipad and the forking started but the percentage stayed at 0%.
2. If that was the case what most likely happened is that the process started and went normally in the background but the status messages were not received by the frontend in the browser. I have seen that myself often enough - one of those nightmares bugs and presumably configuration hassle with the bloody web server.
3. If that was not the case and e.G. filemaker didn't start or some such (in which case you should get an error back, but that might not have found its way to the browser. either), there are 60sec timeouts in place that can kick in if a process is not responding. BUT 60seconds is a minute and that is usually way beyond a user's patience. That should not be the case for admins and testers since it is valueable feedback for me if timeouts fired. You would have gotten a timeout related error message.

So what is the general thing to do: 
a) wait. Wait at least as long as it usually takes to prepare a workstation. In most cases you will find the workstation prepared if you refresh after 2 minutes. 
b) logging in and out is only a useful thing to do if you encounter "csrf" errors (the error message has CSRF in it) or you are explicitly told to try a new login. In this case it was just your session that timed out because you didn't do anything for too long.
c) processes can potentially block each other. An unfinished, errorneous process should not but can block all workstation actions. That can be seen and tidied up in the process manager. Go to administration, menu processes and you get a list of all the processes that are currently running or finished something like 10 minutes ago (the get cleaned up eventually). After each process you can hit a button. A running process would be canceled, a already stopped process would be deleted. Try to find a running process that is not really doing anything and cancel it. It also helps me to have a screen shot of the process list in a hiccup situation.

That's al I can do on that front, I am afraid.

**Comment by urapadmin** [comment]
The error, though, is really weird, I'll should look what could possibly lead to that one:
[MCP_8184_urap_Thu_090720-1837.log](https://github.com/urapadmin/kiosk/files/4903221/MCP_8184_urap_Thu_090720-1837.log)

**Comment by lbestock** [comment]
If not a solution it is nonetheless helpful to have a better sense of what might be going on. And the instruction to be patient (and how patient) is also useful, and the process manager information, and reminders about good ticketing.

**Comment by lbestock** [comment]
I thought I understood but I can't see how to get to the menu processes in administration and am leery of clicking anything I shouldn't, particularly as I know someone is running a process right while I'm trying to look. Can you guide me through it please?

**Comment by lbestock** [comment]
I have been having trouble again on this front. It took three tries (with patience) to prepare my iPad for download from the PVD server. It is currently 12:13pm on 14 July 20, and this has been all within the last five minutes. The first two tries self-aborted:

![image](https://user-images.githubusercontent.com/49291909/87449803-a675ea80-c5cb-11ea-9caa-b56a4ef57ef7.png)

But on my ipad it told me I had cancelled the job: not the case.

![image](https://user-images.githubusercontent.com/49291909/87450084-14baad00-c5cc-11ea-8711-e904ad35f6f3.png)

The third time it looked like it was going to be the same thing, but then patience was rewarded and it ran smoothly in the end. Downloading was just fine.  And now I shall see if I can repeat it with another workstation to get you a running process that is stalled that I can cancel.

**Comment by lbestock** [comment]
No, naturally the others all ran smooth as silk :) The process manager did not update the % once while it was processing, zero to 100 in a blink. But the dialog box on the iPad showed steady progress through both steps in each case, and in each case the whole thing started immediately, too.

**Comment by urapadmin** [comment]
It cannot distinguish between you cancelling and it being cancelled, e.g. due to a timeout. And here the jobs have been cancelled by MCP (who is really on top of things) because they were not doing anything. Before they are not aborted no such job can be started again (you would see a long initializing ... phase). You can speed that up by aborting jobs that are not doing anything yourself: Cancel and then delete. 

I was also running updates and tests on Beset a lot today, that can make things worse. I had strange feedback, too. So far this is all blocky and hiccupy and I will not even try to attend to it. I know how long I will not do anything else and the prospects that I actually find a bug are meagre.

**Comment by lbestock** [comment]
Still not trying to move this to your attention, but I do think I note a pattern worth keeping my eye on. I really only have trouble at "prepare for field". That is consistently problematic (it just self aborted twice for me before running). But I cannot recall having difficult with any other aspects of workstation management and now I will pay attention to see if this is really the case.

**Comment by urapadmin** [comment]
I had reoccurring issues surprisingly during fork (the top progress bar) and not during the filemaker part. I suspecta big database block in the way that's why I smuggled a timeout in with the last kiosk update for PVD. It would also help me to know what you did immediately before the first problem. Did you synchronize right before? Has that always been the case? 
And then as always: I need the time and date to get to the log.

**Comment by lbestock** [comment]
Yes, now that you mention it, it is always fork as far as I remember. I synchronized immediately before. And it was at approximately 1:45pm eastern on 24 VII 20. I will be more vigilant with the next synchronization cycle.

**Comment by lbestock** [comment]
Trying to prepare for field on USTP (so a few versions ago, 0.8.7) and after being patient (in another browser window) I returned to find this:
![image](https://user-images.githubusercontent.com/49291909/88584531-bf48bc00-d01f-11ea-9163-8bd6e8c3058b.png)
It has not prepared to download. In this case I did not synchronize recently, but I have recently been in the file repository where I successfully uploaded images and added contexts to them.

**Comment by lbestock** [comment]
3:40 on 27 VII 20.

**Comment by lbestock** [comment]
![image](https://user-images.githubusercontent.com/49291909/88584773-2d8d7e80-d020-11ea-8b2f-9bb6478b89f2.png)
And 3:44pm again the same thing.

**Comment by lbestock** [comment]
And 3:49, but this time it said it got cancelled (I have never touched a thing in my patience here, and I truly know you can't do anything about it, I am just keeping a record).
![image](https://user-images.githubusercontent.com/49291909/88585316-f1a6e900-d020-11ea-9c81-fc485720760b.png)

**Comment by lbestock** [comment]
I give up for the time being. I cannot prepare this database. I have tried over and over again, before and after an orthodontic appointment, from different workstations. I went to PVD to prepare that one and that worked, but for USTP I am done for the evening.

**Comment by urapadmin** [comment]
I have prepared it. I went to the process management and deleted all processes and then it let me do it. So it is the usual hiccup. And USTP does not have the kiosk version installed that I was hoping to make a difference at least in the way it reacts. 
I will update kiosk for ustp.

**Comment by urapadmin** [comment]
Kiosk updated. The logs don't show anything really useful, but that is how it is with these kinds of bugs, unfortunately.
