### ISSUE TITLE
use a different symbol for clearing an edit field (usually to clear a filter expression)

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#706]
the X has caused confusion. see #702

**Comment by urapadmin** [comment]
- [ ] on the start page in unit selection there is a clear filter button

**Comment by SamKimball-BrownU** [comment]
It is also needed in inventory, I think.

**Comment by urapadmin** [comment]
### 9.4.2
should be there now

**Comment by SamKimball-BrownU** [comment]
So, in inventory there are three fields that you can filter by: Category, view, and find. 

The category and view fields are drop down menus, so I think they should be the new symbol, whereas I think the find field should be an (x) still because it is basically a search box. As you implemented it, the situation is the opposite. But of course, this is a matter of design intent.

**Comment by urapadmin** [comment]
I am still not totally consistent on these things since we invent the design as we go. But I think it is better to have one button icon for all the situations where the content of a field left of the button has to be cleared. The inventory is a good case because so many come together. 
We shall use the backspace button always. The x shall be used for closing pop-overs and modal pop-ups only.

**Comment by urapadmin** [comment]
### 9.4.5
done in the invenory

**Comment by SamKimball-BrownU** [comment]
Ugh. Found another place. Collected material (under registrar tab). Good in inventory though.

**Comment by urapadmin** [comment]
there is always another one ...
### 9.4.7
fixed in collected material

**Comment by SamKimball-BrownU** [comment]
This is resolved, although collected material is one area that seems it needs an update.
