### ISSUE TITLE
File Import Image Upload

### ISSUE THREAD

**Issue by cmrice-arch** [urapadmin/kiosk#714]
Images won't upload with context checked. I tried with all 4 boxes checked, only top ("context from operating system file) and various combinations of other three boxes, also tried various file names:   
<img width="841" alt="image" src="https://user-images.githubusercontent.com/68063513/87311372-24af8f80-c4ed-11ea-97d4-56b26a51da98.png">

<img width="841" alt="image" src="https://user-images.githubusercontent.com/68063513/87311335-1b262780-c4ed-11ea-8f69-fec4b6e7b99f.png">

**Comment by urapadmin** [comment]
Hi Candace,
makes me happy to see a user's ticket. 

### First of all an explanation of how it should be:
To find the identifier in the filename the system expects the filename to be of a certain structure.
In your current case (it is configurable) it has to be just the identifier and then the file extension or the identifier and then a blank followed by a description. Example:
1389.jpeg uploads the file to context 1389. 
1389 this is a funny description.jpeg would attach the image to context 1389 and use the "this is a funny description" as the file's description.
If you upload a file 1389_context.jpg, the system reads "1389_context" as the identifier. 
(Should you for what reasons ever want to use an underscore instead of a blank as a delimiter between identifier and description, I can configure that).

### uploading several files to the same context
You might wonder how to upload 5 files to context 1389 since your operating system would not allow you to give them all the same filename 1389.jpeg. In this case I suggest you call them whatever you want, use the checkbox "defaults" and enter the identifier manually. Form the file itself you only use the date/time:
![image](https://user-images.githubusercontent.com/38838314/87359377-f02ce980-c567-11ea-9e06-07d6d1824577.png)

### limits of the file upload
The file upload has been created to upload a few files occasionally. If you have more than 20 files, you won't stay sane through the process, given that you can only upload something like 5 files at a time (I think that's the limit). What you would want in this case is the import from the local filesystem - a feature you do not have access to with the online server because you would not have access to the server's local filesystem. We would have to strategize with Laurel how to use that feature, if that's what you want. 

Be aware that I have already #694 on my list for the next things to tackle. It will give you the opportunity to upload a bunch of photos without a context and assign a context after the import. That might also help you with what you are aiming for. 

### duplicate images
I have seen in the logs that you also attempted to upload e.G. 695.jpeg and the system did not import it because the image was already in the file repository. I am not sure if you got the right error message back in this case. I will check that. Just to let you know: You cannot import the same image twice. That has nothing to do with the filename, the image itself is compared with all other images on a binary level. If two are the same, the second one is refused. And you should get a correct message - that might be the bug here.

**Comment by urapadmin** [comment]
checked it. The error message looks ok:
![image](https://user-images.githubusercontent.com/38838314/87360562-abef1880-c56a-11ea-8d3f-db4ba26fd595.png)
Have you gotten that one for some of your attempts?

**Comment by urapadmin** [comment]
could be related to #696

**Comment by lbestock** [comment]
A couple of thoughts on parts of this.

Lutz, we have definitely uploaded Uronarti images where the context name comes from the folder, not the file name. That would work best for multiple images of 1389, and in fact is the easiest way to deal with legacy images prior to the ability to assign context after upload. One can go through all one's images and sort them into folders, which is much easier than giving 
them all new names. Was that because we were working off the local server, or can that option be made available for the online version, too?

As for a local server so major uploads can be accomplished, could we configure a virtual machine since you have access to the pc here?

**Comment by urapadmin** [comment]
yes, you are referring to the import from the local filesystem. That needs access to the local filesystem and I am the only one who can access Beset's file system.

**Comment by urapadmin** [comment]
The functionality is the same since I cannot find a general bug. But I have prepared the system so that finding a bug will be easier in future:

### kiosk v0.8.5
 - I have attended to the logging of file imports to get a better insight when the next errors occur
 - some improvements of the feedback. e.g. the message includes the relevant log file now, too. Please report that to me. It makes it easier for me to find the error.
 - I made sure that the little copy & paste feature in case of a refused duplicate image works in Firefox and Chrome

**Comment by cmrice-arch** [comment]
It did give me this a few times and I eventually realized that was a problem with some of the photos that I was trying, but it wasn't consistent, even with the same photo. 

> checked it. The error message looks ok:
> ![image](https://user-images.githubusercontent.com/38838314/87360562-abef1880-c56a-11ea-8d3f-db4ba26fd595.png)
> Have you gotten that one for some of your attempts?
> If you get this one and wonder where that image might be in the file repository, there is a somewhat undocumented feature: You can select and copy the 6e634462-ceab-45c4-9f11-f19bb7873372 and paste it in the file repository into the description filter (it works in Firefox and Chrome in kiosk version 0.8.5). If a file with that uid exists it will present itself. One day I'll find a real solution to do that in the UI. There are so many "one days" already ...

**Comment by cmrice-arch** [comment]
Photo upload success! Now with follow on question! It automatically places photos under "collected material photos". Is there a way to change that / control which category the photos upload to? 
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/68063513/87434573-a7515100-c5b8-11ea-8964-7f0658951f2c.png">

**Comment by urapadmin** [comment]
Good. Progress.

The issue with the ustp configuration is that it isn't clear from the identifier whether it is a collected material or a context because they have the same identifiers. We made that possible in the recording system but it is hacky and has side effects like this one. The only thing we could do is always prefer the context identifier and assign the image to the context. But that means importing collected material photos would produce the problem in the other direction: they would be assigned to the context. 

You promised me that your next project will have dedicated collected material numbers, right ? :o)

Anyway, would that help, because you are only about to import context photos anyway. Or shall I think about a way to let you decide from import to import?

**Comment by cmrice-arch** [comment]
Ah, ok. For us, the collected materials photos are less crucial, so I would say that we switch the default to context photos for now. @Tfranconi would you agree? 

On the collected material (thinking ahead also to the future), do bag numbers work in terms of separate numbers? Small finds get their own numbers, but we have so few (one of the annoying things about the site having easy-to-clean mosaic floors and being abandoned is that the occupants took most things with them when they left - it was very inconsiderate of them!). So most of our collected materials are not the sorts of things that have individual photographs that will be added to the context file and or we're not say going to give each of the 1000 pieces of pipe from a single context 1000 different numbers. For these things, we want tables and charts, not photos. And the tables / charts for most ceramics will be the case for most Roman sites, not just Vacone. Have I just gone off topic on something completely different, or does that make sense here?

**Comment by urapadmin** [comment]
new ticket for the default context ("context" in the system's sense) of the file import:

**Comment by urapadmin** [comment]
as for the bag numbers: Yes. They are separate numbers while we do not currently support a separate small finds number. In fact, we even got rid of one we once had (too many numbers).  If I remember correctly the rationale was that one would bag a small find separately anyhow in the field. So there was never a need to single out a small find from its bag. The system also does not support many small finds per bag. Right, @lbestock?

**Comment by lbestock** [comment]
Right. One small find per bag! Each small find gets its own unique number that way, it's just that it's not a different _type_ of number. URAP FA-001-1 is a bag of broken ceramic. URAP FA-001-2 is a golden statue, and has the small find button clicked. URAP FA-001-3 is a bag of unimpressed sealing clay fragments. URAP FA-001-4 is a single seal impression, bagged on its own because it's a small find. Since it's a database, easy enough to create a list of just the small finds if one wants.

**Comment by cmrice-arch** [comment]
Well, if I really have to stop bagging all the golden statues together... 

Sounds good!

**Comment by urapadmin** [comment]
I leave this open for the time being. If you have been through a few more imports and get the feeling it works, please close it.

**Comment by lbestock** [comment]
I have done a few imports (on USTP even, not PVD, because this fix was earlier). I have had no problems so far importing, though file names for context are a concern, see #811. I also note that assigning context after upload is a huge relief.

Candace, I think you'll use it that way more or less all the time if your photos aren't already sorted by context. The trick there (I can't remember if it's above - I have read so many tickets lately) is to know that if you import a batch of images you can then find them as a single import, instead of being lost in the sauce of all your photos, by searching the tag "import xxxx" with xxxx being the time. You can also name your imports - as I test this I've been calling them "birdbath" or "chaise" so I can more easily find the batches I have most recently imported. The limit on imports at one time is 10 images. So upload 10, assign them their contexts, rinse and repeat, I suspect. Seems to work just fine.
