### ISSUE TITLE
landscape feature or formation process in feature recording?

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#731]
An issue that came up in team meeting PVD2020 is an important one. The issue was raised by the question "is a tree a feature?" 

Two major takeaways from the ensuing discussion.

Natural features condition how people see, move through, and use space, and so are important to record during survey. A stream may not show what people made in the landscape, but the decayed mill on its bank doesn't make sense without the stream and so failing to record it would be dumb. But it isn't a feature per se - feature really does imply human action.

Some things blur the line quite considerably. A line of cypresses beside a drive, for instance, is composed of growing stuff but very definitely reflects human shaping of the landscape. (A canal, too, is different from a stream.) Also raised as an issue in this regard was whether each tree of the line of cypresses is a feature, or if its the line of trees that is the feature (here I am tending to the latter right now - feature recording is not on the locus level for a reason, it's bigger picture). 

Luiza thinks such things must arise in the Amazon project she's worked on and so she's going to do some poking. We have two issues here, one "is this a thing that needs to be recorded" and the other "if so how and what do we even call it".

**Comment by luizaogs** [comment]
I have looked at Amazon stuff -- not from the project I worked on because we didn't have that issue when I was there (I can get in touch with other project members if desired), but have been reading and thinking. The Amazon is a particularly tricky example for this, I think, but I'll get to that in a bit. 

To answer your first question, yes: I think this type of thing should definitely be recorded (funny that it seems to have just occurred to all of us?). I talked to Dan about Petra, too, and apparently this has been a bit of an issue with writing the report for the 2018 season precisely because such things were not recorded as they should have been. 

A few things that came out of speaking with Dan, our earlier meeting, and my readings about the Amazon (in no particular order, though I have tried to make it somewhat sensical): 

1. If the natural/landscape feature or what have you is of relevance to understanding the site and associated features, and perhaps especially if it is something that would need to be referred to in a report in order to properly analyze the space, then it should have a number. Otherwise we're just mentioning a bunch of random, unidentifiable trees (the point you bring up above about recording a tree vs. a line of trees is an interesting one -- I agree that the line of trees seems more useful and relevant). It seems better to be inclusive rather than exclusive in this case.

2. It's perhaps the case that using this type of recording for natural/landscape features would be most useful for things that are not already named. So for example, you don't need to come up with a record number for the Nile or the Wadi Baqa because they are already identifiable. (But then do you still want to record them in some way, or just to say that whatever unit/context you're recording is SW of the Nile or what have you?)

3. I personally do not think I feel comfortable with labeling trees or streams, etc., as features as we currently use "features" -- even if they are somehow distinguished from anthropogenic ones through formation process. I think it would be confusing (think of the wadis -- that's weird, no?). I do think that there will be overlaps constantly -- if there's a natural cave with cave paintings, is the cave a natural/landscape feature and the paintings the anthropogenic feature? Not super sure how to get around that currently, but for planted trees for example I don't think that is such a concern. I think I would be comfortable with labeling them natural features and noting in the description or interpretation if they seem to have been planted in a particular way for a specific purpose (is that always so easy to tell? I wouldn't think so. But then I also don't know if looking at motivation/intentionality is the way to go -- probably not because the tree was planted and now blocks your driveway whether you want it to do that or not). *see caveat about Amazon below

4. Which brings me to: it currently seems to me that the safest and most useful solution would be to have a separate category? The fact that I have been using "natural/landscape feature" here hopefully tells you that I have no idea what such a category should be called, but I think it would be fundamental that it truly serve as an umbrella for all of these things, for consistency's sake. And then trees, caves, wadis, etc. would be different options under such an umbrella, like features are currently recorded in the system.

Now to play devil's advocate against myself with the Amazon example.* One of the major reasons why Amazonian groups have often been considered underdeveloped and not complex societies yada yada yada is because for so long it was assumed that locals had not built anything of substance or left any real traces that they had been there (put very simplistically). But in reality they have been shaping the landscape for a long time -- by planting trees in specific ways (domesticating them, as it were), among other things. So then in that case it almost seems like NOT calling those trees features does a disservice to the material and the people (and seems to have been in the background of the whole issue in the first place). But even so, here I would lean towards making them natural/landscape features (or whatever) and noting in an interpretation that they have been manipulated in certain ways. I think. What this example does suggest is that the use of this category would probably have to be very dependent on the site for it to be meaningful at all (and in the Amazonian case, one would need to get into ontological differentiations of trees and whatnot and this could be a good discussion on including indigenous ontologies in recording systems -- sovereignty! -- but I am not going to go there right now).

Well, that was long. Hopefully somewhat coherent. I love this stuff.

**Comment by urapadmin** [comment]
my modest opinion here is that the line between a feature and not a feature can be very thick and very thin. If there is a tree that fell conveniently so that I can sit on it .... oh no, bad example, uhm ... use it as a table, don't I make it a feature? It is still nature but used for some cultural purpose. Assimilated, so to speak. I would go with feature, too, and just widen the categories. 

That's also the easiest way for me to implement it.  And that counts something, too!

**Comment by urapadmin** [comment]
and then, I thought, staring at the coffee machine, that we must not forget Wittgenstein. Ever. Or at least not when it comes to thinking about terms. Because the question is what particular language game do we play and where and when. In the software we need terms not to kindle an academic discussion (that's a different game) but to express something distinct and to model a data structure, if that data structure is necessary. So I would also try and check how much of the current data structure of features applies to those "natural features" and where does it deviate and what additional information would it need to describe such an entity. The discussion about what the term expresses "archaeologically" is not equivalent and perhaps can be solved on a software level by just making the term for feature configurable.

**Comment by luizaogs** [comment]
Ok I hear you about Wittgenstein and I'm obviously thinking on an archaeological rather than a software level because my brain doesn't work in the latter format (yet? perhaps). 

But I think your example above hits exactly on the issue, at least as I'm thinking of it. If you're using it as a table, sure, I can see it as a feature. If it's just next to your house but affecting how you move to your pool? I have more trouble seeing that as a feature or saying that it has any cultural purpose at all. Admittedly that could be an argument both to lump everything in features and to not do so, because like I said above I do think things will always overlap in uncomfortable ways. 

If you did keep it in features (that term is so misleading! I know, I know, Wittgenstein, but I would then almost want a different term altogether), how would you differentiate between natural features with "cultural purposes" and those more ambiguous examples that nevertheless should be recorded? In interpretations? Formation process? I guess I'm having trouble seeing how that would be done clearly. And also, would all of those options be under "feature type"? Tree, wadi, stream, blablabla, alongside cemetery, inscription, terrace wall? Oof that already stresses me out a little bit, though I recognize that it is because of how I have been conditioned to think of the term "feature" at all. I think the current data structure (as far as I understand it...) for features does apply to "natural features" to a large extent. My issue is more at the higher level of the category itself. If you are keeping it in "features" (and I'm looking at the features tab and trying to envision how I would want to use it) I would almost want features itself to be split into natural (?) and anthropogenic (?), and then have the menus for feature types under those, though again that's an issue because some will not be clearly in either category.

**Comment by urapadmin** [comment]
Lord, stop me. Ha, you can't. In my humble opinion (see, the academic language game needs so much more than just terms ...) a major difference between the humanistic (better than academic, which I cannot say without a provocative undertone)  approach and language game and the role a term plays in let's call it engineering, is that humanism strives to sound a term out, so to speak. And over and over again. And if the atmosphere is healthy it makes its terms resist, shift and budge and tremble and change over time. The worst enemy to humanism is a stale term. That will kindle more papers to question and attack it. And while the understanding gets more and more stratigraphical it gets less distinct. The aim is not determination. Determination is the end of humanism. But determination is the very core of engineering. 
The attempt to distinguish between anthropogenic and natural is obviously futile (no disagreement with you at all here!) and fertile (as demonstrated in this somewhat off-topic discussion) at the same time. It cannot hold as a static distinction but as a dynamic distinction it is very productive. I will always be able to threaten the distinction, no matter how intricate and elaborate the definition of the term gets. What if you build your pool under a tree? In that moment the tree is not anymore accidentally in the way, it is also part of an anthropogenic undertaking and culture reflects back on nature. The other trees I cut down. But that one is allowed to stay because it gives my pool shade. Is it still natural? 
I think we agree that a distinction is impossible and I even believe we agree that it is even undesirable to have a distinction that makes you and any other serious scholar "comfortable". Horrors. 
But Wittgenstein would make cheerful leaps, I suppose, reading how you describe what is in fact the only real weight of a term (and the weight is heavy): 

> Oof that already stresses me out a little bit, though I recognize that it is because of how I have been conditioned to think of the term "feature" at all

Yes! It does. And there is no way around it. And what a wonderful term archaeology chose here: "feature". Ha ha. What the hack is that? I still don't understand why English says "featuring DJ so-und-so". A term once taken in a quandary. Because all the other terms already "meant" something. So one took a somewhat vague and less determined term. Only to turn it into something that now determines your pain. And the reaction? "I almost want a different term altogether". Yes, that's what they wanted, too, then, when they chose "feature". And now it is worn. 

I love this stuff. 

What shall we do? We have to write something on the screen :o) And what icon would I choose for that kind of recording entity? A little tower clearly does not work with that tree shading the pool.

**Comment by urapadmin** [comment]
you guys have no idea how refreshing and exciting a change this ticket is from my reduced existence as the engineer. Determination wherever the engineer turns. If it isn't determined it is clearly a bug. So forgive my bubbling over.

**Comment by luizaogs** [comment]
:) Ha no, this is great! And super useful because I have trouble getting out of the humanistic mindset and your discussion of engineering here gives me a way into thinking at the software level. Now I want to write about the futility and ambiguity of "feature." 

I hadn't even thought of the icon. That's funny. (And yes, using a tower for a wadi makes me stressed, too.)

**Comment by lbestock** [comment]
A small contribution and perhaps a step back, away from the issue of terms and back to what we're trying to do with this section of the recording. (I found this unbelievably refreshing last night already, and that contributed to the crash from running into a teenager - I fell from a considerable height. You guys have made it much more exciting by this morning, but my ability to really play in it has not recovered.)

Locus recording and feature recording are fundamentally different because one gives preference to the actions that LED to something being there, and one gives preference to the actions that RESULT from something being there. We record features (big picture messy category as currently understood) first and foremost because they affect a human's experience of the landscape. We know because they affect ours. It's also exactly why it is important to record things regardless of what the processes were that led to them, and why we're in something of a muddle about distinguishing when those processes were "natural" or not - it isn't the highest level concern with a feature and shouldn't be. But while our primary concern is how do the features of the landscape affect movement/use/perception in that landscape, we do still care about the processes that led it to look like it does. We'll target areas for excavation where we will assign loci and use them to try to capture those processes minutely (removal of each tree is a negative locus, a cut most literally!) but we will focus our areas to excavate on locations where we have judged the features to be man-made. Interestingly I find that I do not agree about how murky the categories are, man-made and natural, because again it's not about the thing itself but about the process. A tree planted by a person is man-made _as a feature_ though not as a tree. It's location and effect on people in the landscape were chosen by a human.

Thank goodness we have an interpretation pane.

I think after your discussion I want to keep the term feature. And publish about it :) Given that we have the healthy interpretation pane, I lean towards having a basic split based on formation process, where it is not whether the thing itself is natural or man-made but whether or not its location and effect in the landscape was natural or the result of human decision and action. Much like locus types, that should trigger slightly different recording - different value lists by feature type for instance, and materials only popping up for human ones. Ha I do still foresee problems from the mudiness - recording trees in a garden as human not natural one still wants categories, like tree species instead of materials, that would rather belong on the natural side. 

On the icon front I've got nothing :)

I will go stare differently at a different coffee machine with mounting dread about a teenager waking up and real gratitude that I get to work on this in this way.

**Comment by urapadmin** [comment]
sobered me. I say let‘s just get rid of the icon. (I don‘t agree with your tree view, though). And let‘s make the term feature a cadidate for configuration. 
So far I have not heard of an alternative term at all, though.

As for the aparently differing understanding about the scope of the term feature among even my most respected archaeologists I do have to point out that less reflecting academics (eyebrow) have not only been let loose on the software but also on the material on site. While I will be able one day to accuse them of not having read the user‘s manual, whose fault will it be that they have not been trained to tell a tree from a tree?

**Comment by lbestock** [comment]
On the other hand, had they been trained they would simply have walked by the tree and not asked at all, since as discussed it might be strangely rare for archaeological projects to consider trees features and I would not have done so previously. And neither the discussion, which seems to have given all of us at least a taste of life, nor the improvements to the way we record, would have occurred. 

I am not any happier not to have an icon than I would be with putting a tower next to a stream! Hmpf. The other icons (I seem to be in a bit of a rut here) are about process, a trowel for digging and a shoe for walking transects. What's the process for feature recording? But in fact I want a fallen tree next to a limpid pool of water with a nice picnic spread on a cloth on the tree, only that doesn't make a good icon.

**Comment by urapadmin** [comment]
my point addresses an earlier statement:
„ doesn't make sense without the stream and so failing to record it would be dumb. But it isn't a feature per se - feature really does imply human action.“. 
Who speaks here? The authority or the text-book. There is - as we have seen - reason to question this deciding factor. Because my tree becomes man made in that I encorporate it in my anthropogenic undertaking. I might not have created it but I recreate it. The tree that still stands after I have cut down the forest around it is still natural but well, I made it outstanding quite literally.
But my point here connects to my former comment: Is there a textbook definition of a feature as there is one for a locus, no matter what they call it?

**Comment by urapadmin** [comment]
more likely they would have been infiltrated with cursory theory babble and record all the trees. There is trained and trained as there are trees and trees.

**Comment by lbestock** [comment]
But there was never a question that your use of it is what makes it archaeologically relevant; that is a separate issue from  whether it is a natural or anthropogenic feature.

The quote is an amusing one because it reflects, not for the first time, the supposed authority speaking as though she is a textbook before rather than after really stopping to think about it. We abandoned that definition of feature (not comfortably) in the course of discussion. How is feature used more broadly? The actual textbook gives a definition that muddies the water yet further. From Renfrew and Bahn's glossary: "a non-portable artifact; e.g. hearths, architectural elements, or soil stains". Their definition of "artifact" I don't even have to look up because it's so burned in my brain: "any portable object used, modified, or made by humans". This definition of feature has to be stretched to use it to define an aqueduct, or a terrace wall, or any of the things that survey archaeologists usually fill in feature forms for. The textbook definition of feature is antiquated; it is referring mostly to things that would be found in an excavation unit.

But still I think by this definition, used a little expansively, your picnic tree can be a feature: it's not portable and it was used by a human. The stream beside it requires more expansion and you can see why most archaeologists, fed this definition, would not jump to calling it a feature. But. If you are using it for refreshment of your eyes and provision of your unchlorinated beverage to go with lunch then "used by a human" is met and indeed it would be a feature.

**Comment by lbestock** [comment]
Record all the trees and the sensory experience of walking beneath their leaves as they rustle in the breeze. Would it be wrong?

**Comment by luizaogs** [comment]
On the icon front, I will make a suggestion that will likely sound ridiculous but that isn't meant to be such: a treehouse. Ha. I think it hits on various parts of what we've been discussing in thought-provoking ways, but I don't know how obscure that would be for one who has not been privy to the discussion. (But now I'm looking at pictures of treehouses instead of reading the Egyptian archaeology textbook I should be reading and kinda want to live in one).

**Comment by urapadmin** [comment]
if I agree that the sensory experience renders all trees feature a for whoever wants to look at them as that I also move straight into the void of relativism. But to come back to our software, if you are of that ilk, your software should be at least configurable towards it. And I don‘t see why not. A configurable listbox should do the trick. And a different project-specific tem.

As for the icon: of course we will have one, just not an edifice.

**Comment by lbestock** [comment]
Now for images I think of Romantic paintings where it's not always clear where the line between a human-built edifice and the mountain it sits atop lies. But again hard to make into an icon.

In a treehouse one could hear the rustling leaves constantly. The plumbing always struck me as a significant impediment.

**Comment by luizaogs** [comment]
There would also be many caterpillars and other types of creatures I am no fan of. Yeah I could never live in a treehouse, but they're so pretty.

**Comment by urapadmin** [comment]
you guy clearly have not been to icon land where all features have the same space: 21 x 21 pixel. Software is limiting!

**Comment by luizaogs** [comment]
That's why I thought of the treehouse! So contained, both anthropogenic and natural _processes_ (unless you think one first planted the huge tree and waited years before building the treehouse, of course). Look how great that is: 

![image](https://user-images.githubusercontent.com/67970402/87551365-9ff87900-c686-11ea-8e50-58a6c2497116.png)

Yeah, I know it doesn't do exactly what we would want it to do, however.

**Comment by urapadmin** [comment]
if you organize it as an SVG I‘ll try it

**Comment by luizaogs** [comment]
SVG coming up. Keep in mind that I did this the uh unconventional way because Chicago sucks and I no longer have Creative Cloud, but it looks ok.

**Comment by urapadmin** [comment]
where is it?

**Comment by luizaogs** [comment]
Oh oops I emailed it to you a while ago. GitHub doesn’t like SVG files, apparently.

**Comment by urapadmin** [comment]
ah, sorry, I overlooked it.

**Comment by urapadmin** [comment]
apart from the treehouse icon, have we decided on anything here in the end? 
- make the word "feature" configurable (one day)
- add formation process or what? Or do we have that already?!? Make that list configurable (I would do that anyway)? Or feature type?!?

**Comment by luizaogs** [comment]
Oh I don't know if we decided on the treehouse icon? That might still be in the weird suggestion phase. 

I'll leave the first stab at structuring this to our archaeological authority, since I can't really envision it myself currently -- but I think what I got from it is that everything would be under "features" and split by formation process (I don't see that in the feature tabs currently) and then different feature types would appear for both types of processes?

**Comment by lbestock** [comment]
I wonder how often Wittgenstein gets mentioned on GitHub?

We have decided that the word "feature" should be configurable one day. I have made a ticket.

Add formation process, as is present on loci.

The materials checkbox list is the potential problem. It is checkboxes not a dropdown currently because a single feature can have multiple materials. Will we be adding more materials, or just new types (which can grow more easily)? I was about to say that a naturally formed feature cannot be ashlar masonry but now I'm back to the reverse of my process: if a tree can be a human made feature then what is an ashlar wall toppled by an earthquake? Wouldn't have been at all without humans. Wouldn't have been in the place it is without the earthquake. I'm less willing to make that one natural than my tree human, but it once again points out why the formation process, while something to record and important to teach people that natural features belong in the recording too, is not the main point. (Weird, though - in excavation I would have no hesitation about formation process for an earthquake-toppled wall being natural, would even be adamant about it. Hm.)

For the time being, do nothing about the materials checklist. I originally thought there should be different materials for natural/anthropogenic. I suspect that over-clarifies the messy middle we keep running into. Teaching and a users manual will have to insist that the most important point about a feature is how it affected things once it was there, not how it got there, and so the formation process should not be structurally overstressed. We have already expanded the materials checklist in PVD2020 and if it gets unwieldy or becomes a problem with naturally formed features then we will revisit this.

**Comment by urapadmin** [comment]
### 9.4.1 
using the treehouse icon now

**Comment by lbestock** [comment]
Wittgenstein IS on GitHub. Not only that, Wittgenstein and trees feature TOGETHER.

![image](https://user-images.githubusercontent.com/49291909/87726210-91948500-c78c-11ea-8ef8-900c1cbf22e9.png)

**Comment by luizaogs** [comment]
Oh that's so cool! And now I'm playing around in there, of course.

**Comment by urapadmin** [comment]
that is horrible!

**Comment by luizaogs** [comment]
I was waiting for your reaction :) How would Wittgenstein feel about it, I wonder.

**Comment by lbestock** [comment]
No one even responds to the so apt use of feature as a verb!

**Comment by urapadmin** [comment]
Where is the preface in this? My god, I can only hope that guy did not get a Bachelor's degree for that.

**Comment by lbestock** [comment]
Is he American? Probably a Masters.

**Comment by urapadmin** [comment]
wow. It hurts. Really, what an original idea that the Tractatus could be visualized as a tree structure given that W himself made these numbers. Wittgenstein would just slap him.

**Comment by urapadmin** [comment]
How troublesome and misplaced the hierarchical numbers in fact often seem (and presumably are) gets completely lost. This is mindless tech crap. Doing something because one can do it.

**Comment by luizaogs** [comment]
He is très français, I think (or Canadian??). And his other projects look similarly...um, bizarre.

**Comment by luizaogs** [comment]
(I just caught the feature use @lbestock. Ha ha ha. Good one.)

**Comment by urapadmin** [comment]
could be confused with nerdiness. At least he bothers to explain that this is not to explain the book. Ouch.

Makes me want to move in to Luiza's tree house and show the world my backside. (It is just now that I write this picture that I think about the refuge of the treehouse in The Grassharp)

**Comment by urapadmin** [comment]
we are also clearly violating the rules of GitHub's Community Guidelines. Which could be visualized in a tree structure as well, I suppose.

**Comment by luizaogs** [comment]
Let's just make trees out of everything now. The Grass Harp, for one.

**Comment by urapadmin** [comment]
That's at least a harder one and would need an original intellectual process than that of the guy who presumably got a master's degree for it

**Comment by luizaogs** [comment]
I'll make a ticket!

**Comment by urapadmin** [comment]
might need a different data structure. Something like a cloud or a network or some such. That, I think, Wittgenstein would like, too. needs its own Github repository.

**Comment by luizaogs** [comment]
I'll leave the structure to you and will come in later to make up nonsense about trees.

**Comment by urapadmin** [comment]
is this here done? I can't tell anymore.

**Comment by luizaogs** [comment]
I think this led to #736 and #744 (making "feature" configurable and adding formation processes to features), so... yeees? With the possibility of needing to revisit it because of the materials checklist.

**Comment by luizaogs** [comment]
Ok I agree with my tired assessment from last night (not that I'm any less tired now) so I close it so you do not have to.
