### ISSUE TITLE
Which server to test on?

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#733]
Now that USTP is actually being used, what server should I test on? Should I do it in PVD, under playground? Should I do it in USTP Test? Should I test some of them without actually uploading?

**Comment by urapadmin** [comment]
as long as it isn't something that needs the USTP configuration, you can use PVD. Otherwise use ustp_test. BUT make sure that ustp_test has the must recent updates (the release list tells you). If not, remind me to update. I am a bit tired of updating 5 servers and tend to make my life easier by skipping some.
