### ISSUE TITLE
What happens if two people edit the same context before they are synchronized?

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#735]
Does this create an error? Does the admin choose which one to accept during synchronization? Does synchronization just fail?

**Comment by urapadmin** [comment]
we use something I coined "pseudo field synchronization". Pseudo because the system knows that a field value has been changed but not exactly when. The gist is that as long as those two users change different fields of a record everything is fine. Only if they change the same field the system will choose the value of that user whose record modification is the more recent one. In real field synchronization a system would manage and compare a field modification date but that is too much overhead for something that in our system virtually never happens.
