### ISSUE TITLE
Filemaker crash when using camera to illustrate relation between contexts

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#748]
Wow. Problems and problems today. I created a relationship between two contexts, SB-001 and SB-002, while in SB-002. I defined the relationship first, then clicked on the small image window, and selected camera. I then took the photo, and when I went to upload it, filemaker crashed entirely

On ipad, PVD

**Comment by SamKimball-BrownU** [comment]
I tried it again, and it worked, although there were a bunch of flashing windows that came up.

**Comment by urapadmin** [comment]
the flashing windows are normal. You experience them often and in locus relations it is particularly awful because I have to create many new records in the background and that is only possible in a new window. I wonder if that challenges the filemaker go ui so that it gets crashy around there. 

Anyway, only if we encounter this here a lot and it is relatively easy to provoke I can try to analyze it. A single fm crash is just bloody filemaker.

FM GO 18 I suspect? Or are you already on 19?

**Comment by urapadmin** [comment]
see #743 which might be connected

**Comment by urapadmin** [comment]
I have not heard of this issue again. and we have #791, so this here can be closed,
