### ISSUE TITLE
A way to reference dayplans

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#767]
I have come across a few times where I want to directly reference a dayplan in a narrative. Would it make sense to just give some sort of id number to the dayplans? Of course, the linking will solve some problems. But what if I want to reference it in some other field? There's currently no way to do that without fully describing the image. 

Thoughts?

**Comment by SamKimball-BrownU** [comment]
I suppose it does give you the date in the bottom right corner of the thumbnail. Would it make sense to replace this with an identifier?

**Comment by lbestock** [comment]
I don't think so; I think the date is often very useful information to have at hand, and the image's unique identifier is a long and unwieldy horror, and creating a more descriptive but still unique id there that is automatically generated in place of the date would have to be something like Dayplan Unit SA 23 VII 20.001. Which, frankly, I still don't think is helpful - if that's the kind of thing you want your image called then give it that description, which serves as a title that can also be used in texts. You don't have to totally describe the image, you can just refer to its title. In most cases I think you should be fine just saying "dayplan". If I'm reading your narratives and you say "dayplan" I'm in fact going to assume you mean the one from that day (otherwise you can say "dayplan from 20 VII 20). Chances that you'd have so many that I couldn't figure it out lickety split are slim. As for a photo, of which there might be more, I still don't think it's more difficult to refer to the title you gave the image. That along with the date will again be enough for me to identify it, and again can go in any text field, not just the narrative. Handily I note that the pinboard gives you the description (kinda like a title) as well as the image and date, so if you're moving between sections pin your image so it's easier for you to remember what to refer to. So I'm going to close this, but I will look out for how you have used it and if I am able to find the relevant images easily!

And we might want to think for the manual about best practices for naming images. In fact they have a ton of stuff already attached to them - context and date most relevantly. So it's redundant to name a photo "dayplan of SA 23 VII 20, morning". You could just name it "morning dayplan" or even "morning" and no information would be lost. And then in your narrative when you say "morning dayplan" and no more, I find it easily enough. In a context description you'd have to say "morning dayplan 23 VII 20" since the date isn't a given in that case, but still not onerous.
