### ISSUE TITLE
Landscape vs vertical: locking landscape orientation on iPad

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#769]
So it is clear that the recording system is primarily to be used in landscape mode. It also seems, and maybe I’m wrong on this, that FileMaker Go allows you to lock off some orientations such that it will only Ever be in landscape mode (when using iPad). See link. I’m assigning Lutz to see if he thinks this is possible.

https://fmhelp.filemaker.com/help/15/fmp/en/index.html#page/FMP_Help/set-allowed-orientations.html

Is this a good idea¿ do others use it in portrait mode ever¿ I just don’t know. It’s something I’ll be  more aware of going forward. But it is a little frustrating when it suddenly flips to portrait mode, and kind of gives a glimpse into the clunkiness of FileMaker.

Would it make sense to make it configurable¿

**Comment by lbestock** [comment]
Some people do like it in portrait. BUT a non issue - it doesn't need to be configurable in FM because the iPad itself allows you to lock it if you have a preference for one way or the other. (Handy, let's me read in bed.) Turn the iPad on. Swipe down towards the middle of the iPad from the upper right corner. This will pull up a set of options, one button of which locks the orientation. You have to be in the orientation you want to lock it in!
![image](https://user-images.githubusercontent.com/49291909/88318948-7de7a200-cce9-11ea-8301-d16014fd5af4.png)

**Comment by urapadmin** [comment]
also: set-allowed-orientation has been dropped from Filemaker in version 16. One of those changes to the worse. 
But in fact I found that often enough the portait mode had advantages and there should be no form anymore that is entirely useless in portrait mode.

**Comment by urapadmin** [comment]
I reopened this because it is definitely worth mentioning in the users manual

**Comment by SamKimball-BrownU** [comment]
My logic for this, particularly locking filemaker rather than using the overall lock screen function, was that I often use other apps in vertical. So, I was looking around for this setting, but it is not possible. 

I'll close this again, because one of the reasons we use the user's manual tag is because it allows me to see all of the tickets that need to be taken into account, even the closed ones.
