### ISSUE TITLE
How are updates rolled out?

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#770]
I am wondering how you update the server. Particularly, I'm wondering if we all have to be synced in order to update.

The situation I'm in, is I downloaded the database that is version 9.4.1. Could you then update it to 9.4.2, and then I download it again with the new version? This particularly affects testing workflow a lot, as there are some tickets that I go to test, only to realize that I'm not in the most up to date version.

**Comment by urapadmin** [comment]
I cannot explain here how updates are rolled out (I still try to explain it to myself whenever I do it and believe me, often enough I don't understand myself). But I can answer your more specific question:
1. Rolling out kiosk usually does not affect filemaker recording unless it is a major update. In that case I would ask everybody to upload and synchronize. If I don't say anything, don't worry (or rather, well, back to my intro).
2. Rolling out a new recording version means that I replace the template that is used whenever a workstation is prepared. The changes take effect with the first workstation that's being prepared. 

If you are "in the field" and want to get a newer version, you have two options: 
- If you have entered data you want to keep, you must you upload, synchronize and prepare yourself a new workstation. 
- If you don't care for your changes you can always reset your workstation in kiosk and prepare and download a new one. 

The latter has one little and rather special caveat: When you opened your current recording version and got the "update successful" message, you must synchronize because your workstation (you were just first) was chosen to receive an update that will disseminate to all workstation only if you synchronize your own. If you got that message and reset your workstation the update (usually configuration keys) is lost. I wouldn't worry at all about it a test scenario - configuration updates are applied over and over again. And in a real world scenario the whole question does not arise. So in short: Ignore the last paragraph.

**Comment by SamKimball-BrownU** [comment]
This is useful and certainly something I need to include in the admin's user manual.
