### ISSUE TITLE
filemaker window menu showing up for admin 

### ISSUE THREAD

**Issue by luizaogs** [urapadmin/kiosk#778]
Here I am supposed to be closing tickets, and yet...

If I'm logged on as admin on my iPad the little Filemaker window menu thing shows up on top of the screen:

![image](https://user-images.githubusercontent.com/67970402/88438203-283cf380-cdd6-11ea-9a73-54361813ae06.png)

![image](https://user-images.githubusercontent.com/67970402/88438264-4b67a300-cdd6-11ea-8783-3f28a9577ad4.png)

It's not showing up for LOGS and I don't know if it's supposed to be there for admins but I figured I would ask to make sure.

**Comment by urapadmin** [comment]
that's by design. It allows me to support teams from afar and ask them to run certain scripts for me. Otherwise that would not have access to them. That is another reason why in a real field season logging in as admin should be the exception. One can mess up a lot if one plays around there. 
Perhaps this behaviour is worth mentioning somewhere in a user's manual.

**Comment by urapadmin** [comment]
well spotted, by the way!

**Comment by luizaogs** [comment]
Ok! Since the users manual is now tagged I close this, then.
