### ISSUE TITLE
complication navigating USTP between file repository and recording system

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#787]
An effect of a non-hierarchical numbering system that I had not anticipated is that it is much more difficult to relate the file repository to the recording system in the way I have been doing for URAP while writing. This is because a file repository image of a context does not tell you what trench it was in. As such, seeing an image in the file repository does not tell you how to find it in the recording in the same way it does with URAP structured numbers - I already can't really do it, and there are only  a handful of trenches (including playground ones). Can we make the trench visible as well as the context in the file repository when the trench is not part of the number? I fear that might be huge, but at least I would absolutely need it if this were my data.

**Comment by cmrice-arch** [comment]
Grr. No one should ever use consecutive numbers. They are terrible for so many reasons. But here we are. Since we're entering numbers manually already, can we modify the numbering by adding the trench? So instead of 1600 we have 5_1600 or 5-1600?

**Comment by urapadmin** [comment]
I cannot easily make kiosk "know" about Trenches etc. That is also not really a topic to be solved in the file repository only. Currently recording system and file repository have to be used together since kiosk does not show recording data or situates an images in terms of recording data. And it won't for a while.

That being said, what I can do in kiosk is show not only the identifiers a file is immediately assigned to but also show the larger contexts. For instance some fictional context 4034 might be located in trench 39. When searching for "39" in the file repository images for "4034" turn up because the locus is part of the trench context. 

I can use this and show all kinds of contexts a file happens to be related to. I would color those differently than the ones the file has been deliberately assigned to. The reason is that if you assign an image to 4034 it will turn up in the context of 39 as well. There is nothing you can do about that so there must not be a little delete button in the file edit dialog to kick the file out of 39. 
Makes sense?

**Comment by urapadmin** [comment]
I would opt for the 5_1600 solution only as a last resort. Although we all agree about the nonsense of consecutive numbers, they are out there not only in USTP. Some people have been defending them no matter how good the arguments against them were. The goal of our system is to allow for such idiosyncracies rather than force people to change. So I would take the opportunity and improve our system.

**Comment by urapadmin** [comment]
@lbestock should you opt for the more pragmatic solution with the prefix we should at least let the identification method add the domain as a prefix automatically. I am just not sure if that's already possible,

**Comment by lbestock** [comment]
I would prefer that we opt for the more difficult solution that shows larger contexts for the very reasons mentioned - this IS a common way of numbering. Lutz, if you do this it would also be visible in the dialog box when one clicks on an image, right? My concern on that front is that confusion is most likely to occur when one is not already operating from any context at all but rather using images to get back to contexts. So it's not that I'm searching a context, it's that I'm searching lithics, then want to go read the context description for the context in which the lithic I have identified as my target on the basis of the photo was found. Currently I can see what context that was, but I can't find it in the recording system because I don't know what trench to look in.

**Comment by urapadmin** [comment]
it will be visible exactly in that file edit dialog and preferably not in the list.

But this also touches the issue of a general search in the recording system which I would expect to be of general use. I believe there is already a ticket for it.

**Comment by cmrice-arch** [comment]
It's certainly true that people still use the numbering system, so you are surely right that it will be worth having a built-in way of coping with it. Anything that improves / facilitates search function is good regardless. Also, the idea of a search function makes me so happy.

**Comment by urapadmin** [comment]
okay, let's try if showing all relevant contexts in the file edit dialog already helps (this ticket) and in addition we give the recording system a search in #797

**Comment by urapadmin** [comment]
### kiosk v 0.8.11

**Comment by lbestock** [comment]
Works and is helpful. However, the larger context is always labeled simply context, and it would be helpful if it could say what KIND of context it is (feature, trench).

What I mean is that here I can see 11 is a trench/area, it tells me so in "directly assigned to":
![image](https://user-images.githubusercontent.com/49291909/89071726-47430480-d345-11ea-8bad-8a06749ccb44.png)

But if I were here:
![image](https://user-images.githubusercontent.com/49291909/89071782-68a3f080-d345-11ea-994d-980f6f1c2feb.png)

I would not know that 11 is a trench. In fact it looks to me like it is a locus, since "context" is the name for locus in PVD. And this means I could not yet use this to solve my archaeological problem in this case (though I suspect that's a weird PVD numbering issue not relevant to Candace, who will be able to use this immediately) - I think I don't know what unit to go look for in the recording data. 

Oh wait and worse - it ISN'T a trench/area, it's a survey unit. This very well may be what you address in your "needs configuration" comment!

**Comment by urapadmin** [comment]
at this point I cannot distinguish between unit types. It is for sure not a context, that looks just wrong. But it will never be a "feature unit" because I need a general term that covers all units types. One should use unit, perhaps.

**Comment by urapadmin** [comment]
11 is a context. It is the invisible context the feature 11 is using. Also something I cannot address in kiosk at this point. Kiosk does not know about hidden loci and all that crap we have because we started with a hierarchical database. We will never get rid entirely of these reoccurring problems as long as the basis of our system is the Uronarti data structure. This is one of those late flowers growing out of that rotten turf.

**Comment by urapadmin** [comment]
The comment about the particular configuration was to remind me and you that it is not a code issue alone. I have to configure it in USTP later, too. 
But I have configured it for PVD.

**Comment by lbestock** [comment]
The rest is more than OK.
