### ISSUE TITLE
search for identifier in recording and jump to the context

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#797]
it would be a good thing to have a free search for an identifier in the recording system and to have the ability to jump to the recording form.

**Comment by urapadmin** [comment]
see #40 which is replaced by this here now.

**Comment by urapadmin** [comment]
### 9.5.1
There is a search button now on the start page. It allows you to type in a full identifier (no wildcards) and you get all record types that have a record with that identifier (test USTP where collected materials have the same identifier!)
Using some more sophisticated filemaker techniques. Please test on Filemaker Go 18 and 19 and on Windows and on Mac!

**Comment by lbestock** [comment]
Very first basic test - this is going to be extremely useful, particularly when one sees something in the file repository and needs to jump to it in the recording. 

First test hiccup: I can only actually get from the search to the context if I'm logged in as admin. If I'm LDB I get an error message that I lack access privileges to perform that action. This is on my Mac. I will test the same thing from the iPad and report back.

**Comment by lbestock** [comment]
Same issue in Filemaker Go. I can search (it's really fast, almost alarmingly so). But clicking to take me to the identified record only works if I'm logged in as admin.

**Comment by lbestock** [comment]
As admin, it works for units, loci, CM, tags (!! - that's cool to discover but won't help in going from the file repository to the recording), not sites which I assume is intentional and makes sense to me.

When I search a survey or feature unit I am given both the unit and its hidden locus, of course; they both take me to the unit. It's funny and might be one of the caveats you mention - it will confuse users who don't know about hidden loci.

Currently it pulls the word locus, too, and eventually it should follow configuration to grab the word used for locus.

All this seems minor to me, but the access privileges you will want to deal with before we roll out to khpp and ustp.

**Comment by urapadmin** [comment]
#### 9.5.2
- [ ] security issue should be fixed for all normal users
- [ ] pulling terms from what is configured for the unit
- [ ] no hidden loci anymore
- [ ] when showing a unit column "in" is the site

**Comment by lbestock** [comment]
Not sure if it is an issue, but when I search for a locus that exists but doesn't have information put in for it that locus does not exist, according to the search. I stumbled on this with NSP-001 in KHPP (which is a unit in the playground).

Otherwise my quick and dirty first test with KHPP looks good. Can't test the term configuration or the hidden loci with this project.

**Comment by urapadmin** [comment]
now that ustp is on 9.5.2, too, you can finish your test.

**Comment by lbestock** [comment]
Works!
