### ISSUE TITLE
excavating/feature recording needs its own icon and term

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#798]
The excavating/feature recording units have a trowel icon on the start page but a treehouse icon in the recording form. They should not have either, they would need something new (and in fact also a different term than feature recording. That's for a new ticket after 9.5:

_Originally posted by @urapadmin in https://github.com/urapadmin/kiosk/issues/674#issuecomment-665775464_

**Comment by urapadmin** [comment]
new term necessary. As for why this recording method exists in the first place:

> Here is our answer as to what the purpose of the excavating/feature recording method is:
> https://github.com/urapadmin/kiosk/issues/789#issuecomment-665675211
> Laurel puts in Wheeler's old legacy excavation (!) in. But since we don't have Wheeler's locus records but rather features (his rooms), we needed to collect features instead of loci. Apart from that we needed the normal excavation recording form, with dayplans, narratives and all. And that is why I used the simple excavating form and extended it to show features instead of loci.
> 
> So much for the history

**Comment by lbestock** [comment]
My head cannot currently think of non-legacy data applications for this, but I don't trust myself. I comment because I am thinking about it, if not productively. Since it is legacy data connected in my head the terms and icons (pith helmet) that suggest themselves to me are in that vein, but wouldn't a pith helmet, funny to me, be problematic in broader application?

**Comment by urapadmin** [comment]
I get Luiza in on this. As the inventor of the treehouse, she is our expert in icons for excavation methods.

Apart from the icon we also need a term, which might even be more important.

**Comment by luizaogs** [comment]
Hardly an expert, but am thinking about it. I do think the pith helmet might get you some raised eyebrows :)

I can't really think of how this might be used for things other than legacy data, either, but I am currently brain dead so take that as you will (but what in the world wouldn't be covered by the other available excavation methods?). IF we cannot think of totally different ways in which this can be used, I suppose framing it more broadly as "integrating records" rather than strictly legacy data might be useful for other projects? In that vein an icon dealing with records rather than digging comes to mind (maybe something like sheets of paper because legacy data is on paper ha), but I'm not sure if that's what you're looking for.

**Comment by urapadmin** [comment]
you guys discuss that out...

**Comment by lbestock** [comment]
I like the idea of paper or an icon of a physical notebook a lot. Definitely better than a pith helmet. But leave it open for a bit longer, please, and we can discuss it when we are a little more human.

**Comment by urapadmin** [comment]
I turn this into a github discussion. But you guys should get to being human enough to get to a conclusion here.
