### ISSUE TITLE
Fully Testing Locus Relation Image Containers

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#799]
This is a new ticket for fully testing the image containers in locus relations. This came as a result of #743 

Things to look out for:

Multiple relations. Can two loci have more than one relation between them? I'll check it out. 

Go between the different loci.

**Comment by urapadmin** [comment]
Ah, Don't test the thing with two loci having two different relations because that is part of a big archaeological discussion that lead to #614. So that will change anyhow. It is really a through test of the image container using our guidelines in the wiki that we most need here to make sure that my last changes have not have new side effects.

**Comment by SamKimball-BrownU** [comment]
See also #748

**Comment by SamKimball-BrownU** [comment]
As far as I can tell, it is all good.

Took me long enough to get around to testing this, my goodness.

Tested on windows using database version 9.5.2

However, see #748 for hiccups when using iPad. Just something to keep an eye on, but I haven't been successful in recreating it.

**Comment by urapadmin** [comment]
I close this. It is a duplicate at this point.
