### ISSUE TITLE
synchronization failure for non-image related reasons

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#804]
I have failed a synchronization at 1:20pm Eastern on 31 VII 20. I do not understand the error:
![image](https://user-images.githubusercontent.com/49291909/89060481-1b1d8880-d331-11ea-8016-44a3ba451c31.png)

I do know I was trying something that I was skeptical about: changing the identifier lists per workstation. Thanks in part to my giving feature and survey number lists that overlapped, multiple people had run out of available numbers. So I changed the ID method for survey to be 3 digits instead of 2, and created new number sets for all the survey and features for all workstations except my own. Very possibly I did not think through adequately what those would be, but I did not get any warnings when I made them.

**Comment by urapadmin** [comment]
no, that is an issue with a configuration key. Strange that we have never run into the issue before since configurations can be synchronized: I have introduced a new key "help_feature_recorded_in_list" with the last update and all workstations try to add this one which leads to duplication. Synchronization does the right thing. 

I have to think about a new mechanism for the particular issue of introducing a configuration key into a running field season (pretty rare, if you think about it).

Here I have solved the issue manually and synchronized for you.
