### ISSUE TITLE
image added through file import lacks date in recording system

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#812]
I uploaded images through the file repository with box checked to get context data from the image file. Subsequently I attached a context to that image in the file repository (LA). I then downloaded my database and opened it in Filemaker to check that images are where they should be after being assigned this way after import. They are! But they lack their date, which is usually shown. Is that a problem? I'm not sure, and which date would we want: image date (which would have required clicking different boxes in the import) or import date? I think I lean initially towards saying it should have the date of the assignment to the context. In this case that was the same as the import into kiosk.

What I don't know yet is what would happen over time, if some images were being imported like this but the unit was also being worked in and having ipad images added. Would the dateless images always float to the top? That is what I do not want to happen and why I think date should be "date of adding to the recording system" which is "date of having its context assigned to it".

![image](https://user-images.githubusercontent.com/49291909/89088220-35715980-d365-11ea-9a2d-909fc63e3e28.png)

**Comment by lbestock** [comment]
![image](https://user-images.githubusercontent.com/49291909/89088259-589c0900-d365-11ea-85ac-a84dbacb8d23.png)

It knows the date of being added in locus.

**Comment by lbestock** [comment]
And in collected material:
![image](https://user-images.githubusercontent.com/49291909/89088303-88e3a780-d365-11ea-8281-c0b0e1826502.png)

**Comment by lbestock** [comment]
(This is accidentally very confusing because my image import was a bunch of screenshots. They were handy. I wasn't anticipating problems.)

**Comment by urapadmin** [comment]
I think we should give it the upload date. It's all we have in file upload (unless we use exif data or qr codes). When importing from a file system the actual date can be used but that is not possible when uploading.

**Comment by urapadmin** [comment]
not sure, do you think that is an immediate issue for ustp?

**Comment by urapadmin** [comment]
is possible that you did not use "get date from file"?
![image](https://user-images.githubusercontent.com/38838314/89107608-81d69b00-d432-11ea-94a6-a939ac3ec326.png)

**Comment by lbestock** [comment]
I agree it should get the upload date. I don't remember which boxes I checked, but since the date is given for collected material and locus photos from the same import, outside of dayplans the system already has the means of grabbing the date properly.

I don't think this is super critical in that it would keep ustp from working currently.

**Comment by urapadmin** [comment]
> 
since the date is given for collected material and locus photos from the same import, outside of dayplans the system already has the means of grabbing the date properly.
> 

I don't understand. The system takes the date and time from the file. That's all it knows at this point (context from operating system file). And that happens to be the timestamp of the upload. And as far as I can see on PVD and USTP you did not check the "get date from file" checkbox. Check it.

**Comment by lbestock** [comment]
The discrepancy might be because the date on the dayplan is not a "modified by" stamp of the new sort, and the date in the other two locations is. You're most likely right that I didn't check "get date from file" - trying it once I put together some smaller jpgs so I can quit burning rainforests quite so rapidly...

**Comment by urapadmin** [comment]
I still don't understand what that has to do with anything. The dayplan's modifed by and created by timestamps will definitely be the current daten and time. There is no way around it. It is only the image's own date (which even different from created by and modified by of the image record itself) that gets set by the file import. In the end it will all be very close because it all happens more or less at the same time, BUT: If you import from a qr code, the modified_by and created_by timestamps will still always be the current date and time. The qr code would only set the image's own timestamp (when has it been shot? Which is different from when has it been added.)
So I have the feeling you have something entirely different in mind here (and it has nothing to do with the original issue that the file did not have any date at all)

**Comment by lbestock** [comment]
A dayplan doesn't display its created and modified by information, though. That's why the import without the "get date from file" box checked has no associated visible date to a user in dayplans, but the images from the same import in CM and locus do. For me as a user if I forget to click that box then the dayplan has no date on it.

Are we confused about nothing? We know why the dayplan had no date from the import - definitely the box clicking issue. There is no bug, only a workflow issue.

It just makes me wonder if the date on the dayplan shouldn't be the created/modified date that is nearly everywhere else now, too.

**Comment by urapadmin** [comment]
there is no question that the get date checkbox should be checked (if that's where the date should come from, remember there are other possibilities like the default or exif data).
Apart from that I was just trying to understand what you were trying to tell me. The modified_by and create_by dates of the dayplan record would be changed if somebody changes the dayplan description. The file_datetime, if that is the one you see, is indeed supposed to be the time when the photo itself was shot. In the case of the file upload I have always been even hesitant about taking that date from the file because it is in fact always wrong. That is why the get date is not on by default. It produces wrong data.

**Comment by urapadmin** [comment]
If ustp want to import data they should really rather think about using an import from the local filesystem. There the created_by timestamp should always be the date when the file was first stored by the camera.

**Comment by urapadmin** [comment]
what SLR has been used on USTP? Perhaps it has exif data, too? (exif data can be different between Canon / Olympus / Nikon as well and we would be interested in getting our hands on such files).

**Comment by lbestock** [comment]
![image](https://user-images.githubusercontent.com/49291909/89110725-93f90f00-d41b-11ea-94a9-8e7b601238bd.png)

What I see here in dayplans is the file_datetime? It's in special archaeological date format.

In Filemaker there really is no created by/modified by visible in dayplans. The only date is the one you see there on the screenshot, which, as you note, has to come from the file, usually no problem. The created and modified by are visible for the dayplan when I go to it in the file repository, of course, but not in Filemaker.

**Comment by urapadmin** [comment]
no. Those are the created by and modified by timestamps of the image record itself (which is still not the image itself, since the image record can also have a description: the context independent description - think about candids!).
I am sorry, it is complicated. We have many many timestamps. 
That that one in dayplans is the actual file datetime (when the photo was shot) is only an educated guess. I have not looked it up.

**Comment by urapadmin** [comment]
if you want to see modified by in dayplans in filemaker, file a request.

**Comment by lbestock** [comment]
I think this is a test case issue that in fact looks like more confusion than is really there. There's a timestamp. It's good.
