### ISSUE TITLE
pin and date disappear when one clicks on the date in dayplan images

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#813]
Weird tiny bug discovered very accidentally. In dayplans when in Filemaker on my mac in 9.5 if I click on the date displayed at the bottom right of the thumbnail of a dayplan, both the date and the pin that allows me to add something to the pinboard disappear. They come back if I click on another dayplan and then back again.

Before I click on the date:

![image](https://user-images.githubusercontent.com/49291909/89088424-32c33400-d366-11ea-8851-4b4c81253c8a.png)

After I click on the date:

![image](https://user-images.githubusercontent.com/49291909/89088440-41a9e680-d366-11ea-880d-911950073631.png)

**Comment by urapadmin** [comment]
that's not really a bug. In fact the controls disappear whenever you click on the image because they are on top of it. The date is not clickable so it is the image itself that gets clicked. If the image gets activated it comes to the foreground. It goes back as soon as you leave it again.
It allows the image, which is small anyhow, to use all the possible space. Should it happen too often that you miss the pin button and instead activate the image it would be worth changing this. So far I think it is better to allow the image as much space as it can get.
