### ISSUE TITLE
things on the radar for USTP image file imports

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#817]
For many reasons it would be better to do a local import instead of an upload. Three such reasons: 

- creation date of the image is saved
- more images can be imported at once
- rainforest 

What kind of camera(s) resulting in what kind of files and exif data are we talking about? 

Contexts assigned on the basis of file names have potential problems. Contexts with spaces in them get split (I don't think that is a problem here but can't recall). But definitely an issue: "5" is presumably the number of both a trench and a context.

**Comment by urapadmin** [comment]
you can cross out the rain forest. Since USTP is on Beset we will have to upload those photos to the server's filesystem anyhow. I would just do it using direct access. So we would need the images on a harddrive and you plug it in to the local hillside server and I use that one to copy the files to Beset. And there I start the local import.

Remember that kiosk was not planned and should not be a mere online system. Here is one of the reasons.

**Comment by Tfranconi** [comment]
We have two main cameras:

Canon EOS 5D Mark III
Nikon D5100

They both can produce raw and jpg images, and the exif is extensive (here a
screenshot only of what fits on my screen):

[image: image.png]

I have no idea what rainforest means, but hopefully this is helpful.

best,
Tyler

---

Tyler Franconi
Visiting Assistant Professor of Archaeology
Joukowsky Institute for Archaeology & the Ancient World
Brown University
Box 1837, 60 George Street, Providence, RI  02912, USA
tyler_franconi@brown.edu

**Comment by urapadmin** [comment]
the rainforest is more of an insider I always bring up when we waste digital resources ...

As for the cameras: Are you guys meticulous about settings your camera's current time? So that the timestamps in the exif data are in fact real? And could you please upload 2 photos (raw) from each of the cameras with exif data included? Then I have specimen I can put under my microscope. 

(if you upload images, it seems, you really have to go to the github page and paste them in the browser).

**Comment by urapadmin** [comment]
ah. You also won't be able to upload raw files here. They have to be zipped or github won't accept them.

**Comment by Tfranconi** [comment]
I don't think I have the raw images for the Canon anyway, I'd have to ask
Gary. Do you want me to upload jpegs?

---

Tyler Franconi
Visiting Assistant Professor of Archaeology
Joukowsky Institute for Archaeology & the Ancient World
Brown University
Box 1837, 60 George Street, Providence, RI  02912, USA
tyler_franconi@brown.edu

**Comment by urapadmin** [comment]
unfortunately, that would not help. It is the raw files we would want to 
import, normally. The system itself turns them into jpegs for all kinds 
of purposes but the raw file is always the "original" we store 
permanently and never temper with.

Am 02.08.2020 um 01:02 schrieb Tfranconi - notifications@github.com:
> I don't think I have the raw images for the Canon anyway, I'd have to ask
> Gary. Do you want me to upload jpegs?
>
> ---
>
> Tyler Franconi
> Visiting Assistant Professor of Archaeology
> Joukowsky Institute for Archaeology & the Ancient World
> Brown University
> Box 1837, 60 George Street, Providence, RI 02912, USA
> tyler_franconi@brown.edu
>
>

**Comment by urapadmin** [comment]
Oh, don't worry. I found sample raw images on the Canon web site. That should be enough to develop an import.

**Comment by cmrice-arch** [comment]
Soooo. The dates on the photos are correct, but I'm afraid that I turned off raw files on the Canon in 2017 because we ran out of storage... We have raw files from 2016, but not after.

**Comment by cmrice-arch** [comment]
Clarification - raw files from 2013-2016.

**Comment by urapadmin** [comment]
well, that is ok with me. Then those jpegs are your originals. It turns out after a short test that we won't be able to process Canon raw files (.cr2) right out the box at this point. Only Nikon's .raw format works. 
new ticket #818

**Comment by urapadmin** [comment]
News: Import of Canon raw files now supported by kiosk 0.8.16. So on the file format front we are all set for USTP.

**Comment by lbestock** [comment]
I think this can be closed, right? We can import Canon images. And now that context can be assigned after import the whole thing is much more flexible. But we're still necessarily on the online server with an international team, so 10 images at once. The system file is a reliable way to get the date attached when importing.
