### ISSUE TITLE
Upload failed for unknown reasons on Alice

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#822]
Perhaps related to #807 

When uploading data for alice, it got to 100% and then gave this message

https://share.icloud.com/photos/0Af3l9zoVfGIy5FfpqcvXNNRA

**Comment by urapadmin** [comment]
and then your second attempt was successful? Happens -> indeed a hiccup.

**Comment by urapadmin** [comment]
you don't need to bother too much relating these hiccup tickets - they are all connected by the label hiccup.

**Comment by osiegel14** [comment]
I had repeated issues trying to upload my database. Perhaps this is because of my household's extremely slow internet connection: it doesn't drop out, but download speeds top out at around 3.0 mbps and upload speeds allegedly top out at 0.6 mbps. The error message I got simply said "objectObject", and can hopefully be seen in the screenshot below. I wonder if as Laurel suggested it is simply timing out? It usually could get to about 80-98% (which often would take almost half an hour) before it crashed.

![image](https://user-images.githubusercontent.com/68746088/89310376-37c00600-d63a-11ea-940a-60f674929f59.png)

**Comment by SamKimball-BrownU** [comment]
> and then your second attempt was successful? Happens -> indeed a hiccup.

yep, second try was successful

**Comment by urapadmin** [comment]
@osiegel14 
It is very hard for me to find you in the log files in this case without knowing a time when the message occurred. Do you remember the time?

**Comment by osiegel14** [comment]
I'm happy to try uploading again since the message was produced pretty consistently, but the message in the screenshot above occurred this morning occurred between 9:45-9:55am.

**Comment by urapadmin** [comment]
where in the States are you? Are you in the same timezone as Providence?

**Comment by urapadmin** [comment]
found you. But the logs don't show anything. This seems to happen somewhere beyond our software. So I have lifted a timeout on the web server from 20 to 40 minutes. And now I have to ask you again to upload.

**Comment by osiegel14** [comment]
Sorry for the confusion: I’m in Chicago, so Central time: 9:45-9:55am CST,
10:45-10:55am EST

**Comment by osiegel14** [comment]
Currently uploading now. I will report back on success or failure as soon as I can

**Comment by urapadmin** [comment]
please make sure that while uploading your computer does not fall into any sleep mode and the browser tab is visible. I you can.

**Comment by osiegel14** [comment]
Success!

**Comment by urapadmin** [comment]
alright. Not that I really believe my change did it but let's see in another round if trouble reappears.
