### ISSUE TITLE
Syncing duplicate tags: what will happen?

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#823]
This is relevant because I need to know how to warn users (particularly admins) if this is a problem.

Hypothetical scenario:

- two different people (devices) are out in the field
- they both say "wow, we have a bunch of benches"
- They each create a tag that is "bench" with category "outdoor furniture" and no description. I.e. completely identical
- user 1 comes back and uploads data
- user 2 comes back and uploads data

What happens when they try to sync then? And, then, how does the admin go in and fix it?

As for work flow, this information will need to be added to the wiki in some form. I looked around for it, and I couldn't find it. I can add the information that you give to me to the wiki, but where should this go? Perhaps somewhere in the developer's manual? 

Regardless it will be included in the user manual (particularly, for admins, and depending on the severity of the ramifications a warning can be included in the guide for general users)

**Comment by urapadmin** [comment]
the answer to the question: two tags added at the same time should not happen. Highly theoretical because that is not the workflow with tags. In a real scenario they are assigned in the analysis phase and not while recording. But of course, theoretically that could happen and the system would synchronize them as two different tags, just that there is hardly a way to distinguish them.
On the way back to the workstation I am not sure, could be that preparign the workstation failed because of a key violation in filemaker. You may test this.
Let's assume that's not the case, then filemaker would have two different tags, too (and you would hardly notice). Which does not make much of a difference because when searching for a certain term both tags would be found. 
Nonetheless, if the case gets noticed, the way to repair it would be to create a third tag and to go through all the loci and features with the old tag and switch to the third tag.

**Comment by urapadmin** [comment]
as for workflow: This information (you mean the answer above, I assume) goes in the wiki in the user's or admin's manual. And we will find it there. 
The developer's manual is for developer stuff. 
Does that answer your question?

**Comment by SamKimball-BrownU** [comment]
All makes sense! I tend to worry quite a lot about tags because they are such an open structure, that users may try to utilize it to make up for a lack of a software feature (or a perceived lack of a feature....)
