### ISSUE TITLE
Replacing images on iPad replaces all instances of images

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#833]
If you use the iPad context menu to replace an image, ALL instances of that image are replaced with the new one. The image is replaced in the gallery, and therefore, all usages of the image.

For example, say I used an image in both dayplans and collected material. Then, I decide to replace the image in dayplan, by clicking on the image container and then selecting "replace". Then, the new image that I choose to replace it will not just replace it in the dayplan, but also in the collected material. And, even worse, in the gallery! So, if you don't have it somewhere else, then you just lose the original photo (that you were replacing) forever. 

This is certainly on the filemaker/system level. Is there any way to suppress it? or otherwise limit the ramifications? If it cannot be fixed, I will include it in my warnings in the user manual.

**Comment by urapadmin** [comment]
that is not a bug at all. That's the same thing as drag&dropping an image over an existing image or using copy & paste on an existing image. And it is correct that the image gets changed and if it is linked at different places it gets replaced. That's in fact the reason why linking is better than having duplicates.

Or do I misunderstand the case?

**Comment by SamKimball-BrownU** [comment]
I suppose not a bug, so I remove the label. But, the ramifications of choosing to replace an image are a lot larger than it would appear at first.

**User manual solution** seems best in this situation, although a warning popup would be nice (similar to drag and drop, although I understand that filemaker is finicky even at the best of times). It is rather serious to replace every instance of an image. 

It is also worrisome, to me, that the old image appears not to be saved anywhere. Is this correct? Or does it stay in the gallery under some weird tag?

**Comment by urapadmin** [comment]
this is a matter of perspective. There are not several instances of an image. The whole idea of the gallery is that every image appears only once in the gallery and shows up in different contexts. But it is the same motive. So If I make a dayplan and that dayplan also appears in locus photos and afterwards I realize that the dayplan had something missing, I can change it. You have to ask yourself: Why did you CHANGE an image somewhere? That's not what you usually do except if the old one was wrong and in that case you WANT to change it and the changed image appears in all recording situations where that motive was attached for a reason. 
So the image cannot appear somewhere else in the gallery because it has been changed. It cannot live under some weird tag. Later in kiosk synchronization stores changed images in a archive folder, but that saves only those images that had been through synchronization before. If you add and change an image in the same synchronization cycle, the first version of the image is lost.

An analogy: If you go to a narrative and change it instead of making a new one, you also don't wonder where the old one is. You changed it. Images are like that when it comes to modifications. 

There must be a reason, I mean a scenario why a user changes instead of adds an image. It is crucial to make users understand that linking an image in three different places in the recording system makes the SAME image visible in appear in different recording contexts. But there is always only ONE image. It is really pretty much like our wiki discussion. Our software does not operate like google docs, it rather operates like the wiki - which has images in the gallery and only there. It is just that we allow to save a new image and link it at the same time when one enters an image for the first time. Otherwise we would have to make our users go to the gallery first, upload an image and then in a second step link it to a recording context. That is how the wiki does it. And we both know it is cumbersome in the wiki :o)  It would be even more so in our recording system.

As for a warning: Hm. The issue here is as with drag and drop (and particularly in the case of drag and drop): I cannot suppress the process. So instead of a warning I would inform the user that the image was replaced and hence the former version eradicated from the system. That would not be very helpful. 

@lbestock : We could think about a general rule not to allow modification of images at all in the recording system. But that is a principal design discussion. The real issue for the current design is that users need to understand the nature of the image management. And since user's intuitions come from copy & paste rather than from knowledge and database backgrounds, they are bad intuitions, so to speak. They have to learn a new intuition from the user's manual or from training.
