### ISSUE TITLE
"locus" analysis data widget

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#879]
- whatever loci are called
- should show context id (locus), 
- the domain's context id (unit), but only if no domain is selected
- the modified_by field, but only if no person is selected
- type
- number of photos
- number of lots
- number of relations
- is description filled?
- date of creation

**Comment by urapadmin** [comment]
@lbestock: we show those loci that have been MODIFIED on that day (as normal for the other widgets), not only those that have been created, right?

**Comment by lbestock** [comment]
Yes.

**Comment by luizaogs** [comment]
By "whatever loci are called" do you mean that the widget label should match what they are called in a specific project? If so, not the case currently -- PVD has contexts but in the director's view they are called loci.

Currently there is no unit number separate from the locus number (without a selected unit).

There is no recorder, either (when no recorder is selected).

There is also the bonus of the interpretation? column not mentioned above, which I guess is due to #908.

![Screen Shot 2021-06-30 at 10 01 25 AM](https://user-images.githubusercontent.com/67970402/123965560-f1c70b80-d98a-11eb-9307-4077fe99272c.png)

**Comment by urapadmin** [comment]
> By "whatever loci are called" do you mean that the widget label should match what they are called in a specific project? If so, not the case currently -- PVD has contexts but in the director's view they are called loci.
will be addressed by

**Comment by urapadmin** [comment]
the additional interpretation is okay.
