### ISSUE TITLE
f092 does not show up on either 14.I.2019 or 9.XII.2019

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#920]
images for f092 have been modified on 9.XII.2019. But on that day the feature does not  show up at all.
It  does show up in the context selector on 14.I. but not in the feature list and there  is also no image on that day.
Clarify!

**Comment by urapadmin** [comment]
f092 is in the context selection list because its hidden locus f092-001 has been last modified on that date. This will be in fact always that way since the hidden locus will always have a modification-date that equals the creation-date. It never gets updated because it is not visible.

The director's view does not show any data in the other widgets on that day because everything else connected to that unit had been modified later.

      "modified": "2019-01-14",
      "identifier": "F092",
      "record_type": "locus",
      "primary_identifier": "F092-001"

      "modified": "2019-01-16",
      "identifier": "F092",
      "record_type": "dayplan",
      "primary_identifier": "F092"

      "modified": "2019-01-16",
      "identifier": "F092",
      "record_type": "feature_unit",
      "primary_identifier": "F092"

      "modified": "2019-01-18",
      "identifier": "F092",
      "record_type": "dayplan",
      "primary_identifier": "F092"

      "modified": "2019-01-18",
      "identifier": "F092",
      "record_type": "unit",
      "primary_identifier": "F092"
 
So as for the director's view there is no real error here. It just unfolds that way when looking back.
