### ISSUE TITLE
create admin user before fork

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#931]
### todo
- [x] if there is no admin excavator (the users of the filemaker app), kiosk needs to create it before forking. This cannot happen in filemaker or several workstations would create competing admin users with the same name.
_Originally posted by @urapadmin in https://github.com/urapadmin/kiosk/issues/378#issuecomment-775349472_

**Comment by urapadmin** [comment]
in fact one day the user management should move to kiosk entirely.

**Comment by urapadmin** [comment]
not for v1. But I should use a trigger here and think about how to do this in a less project-specific way.

**Comment by urapadmin** [comment]
### @test 0.9.2
ja, no, I don't invent anything new here. We just use a cross-table migration script that can be disabled for projects that don't use the "excavator" table the way urap does.

**Comment by lbestock** [comment]
Configure team in FM to have no admin user. Import. Admin should be gone only you'll not find out because in the next fork, a new admin should be created. So check that you can sign in as admin.

**Comment by luizaogs** [comment]
This worked as it should, I believe (judging from Laurel's comment above), and I then synchronized so that there would only be one admin password. 

But before I imported the admin-less database I opened it to make sure there was no admin user and got this screen:
![image](https://user-images.githubusercontent.com/67970402/120712439-0224bd00-c497-11eb-91d1-6f18bab6bd89.png)

I was able to set a password and everything, and the admin user was back in the list of team members too. Fret not, I then deleted the admin again and then imported the database before I could create a new admin in FM. But is the FM admin creation correct? Your comment above confused me a bit, Lutz, so I thought it worth checking.

**Comment by urapadmin** [comment]
you deleted the admin in FM and then uploaded that database and imported it? 
At what point did you get the admin creation hint? 

What should happen: If you delete the admin in FM and synchronize that database, the admin will be deleted. BUT next time you prepare and open a database it will be recreated, and that is when you should see the alert above.

**Comment by luizaogs** [comment]
I got the alert before importing it - I opened FM between deleting the admin and importing the database to make sure the admin was actually gone. Hence my confusion.

**Comment by urapadmin** [comment]
yes, that is what I would expect. The admin user is always created if you open a database that does not have an admin.
I think, you have quite thorougly tested this :o)

**Comment by luizaogs** [comment]
:) Bye bye ticket.
