### ISSUE TITLE
add date in file repository for imported images

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#960]
PVD unit LA we noticed four dayplans that had no date attached. This seems to be what was fixed in #67 (not yet tested) but we further noted that it is not possible to add a date for images that came in without one.

**Comment by urapadmin** [comment]
The edit field was disabled for images that are context-bound. For candids it worked. Insofar it wasn't strictly wrong since it follows the premise that data recording is only done in the recording system and not in kiosk. I will make a general exception for this one field since it cannot be set at all in the recording system. It is automatically generated on creation of a photo.

**Comment by urapadmin** [comment]
### @test kiosk 0.10.1
- [ ] The field can be edited now (if the user has modification privileges, that is)
