### ISSUE TITLE
file picking: some images dummies and some not

### ISSUE THREAD

**Issue by lbestock** [urapadmin/kiosk#969]
Just downloaded 10.3.5 to give myself epilepsy with the flickering. Dayplans in LA are a mixture of dummy and real images:
![image](https://user-images.githubusercontent.com/49291909/110224634-3f36de80-7eab-11eb-97c0-764c80396317.png)

I also don't know why one dated 9 VII is on top of one from two days ago. But I can make new (flickering) images without crashing FM.

**Comment by urapadmin** [comment]
- The first, date 09.VII is a0036147-f453-4b8f-a81c-cfcfcefd5fb9: It is also connected to SA-004
  - the second, date 09.VII is a109412e-8a98-43da-8121-9e1c477f9cd3: also connected to SA.
  - the ones that are just empty images are indeed not connected to any image record, so that's okay, too.
 
Ergo: File Picking did what it was supposed to do and we learned again, that things are more complicated than they seem.
I will think about this again conceptually, but the ticket itself can be closed, I think.
